### ISSUE TITLE
Atom plugins is up for graduation

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#104]
Atom plugins is up for incubation renewal, as it was approved 2019-01-01

**Comment by jmertic** [comment]
From previous TAC discussion, looking for insight from @johnarwe on status and progress towards graduation.

**Comment by johnarwe** [comment]
@jmertic, please help me refresh my memory here; my email archive is not really helping.  IIRC, Herr Egeler became the rep/lead for this project along with TerseDecompress "some time ago", so I've been letting him respond.  If I have the roles & responsibilities wrong though, that obviously won't function.  

That issue aside, reading through https://github.com/openmainframeproject/tac/blob/master/process/project_stages.md I'm unclear what the following means exactly when it refers to trademark.  I'm not aware of any trademarks held by the subject project (or any other, in truth).

> In the case of an Incubation Stage project that is not renewed with OMP, the trademark will be returned to the project maintainers or an organization they designate.

On my own personal front, with respect to this project things have been almost completely silent.  When my job changed focus about 2 years ago, my new area only uses Rexx (of the language plugins in this project), we don't touch the Rexx very often at all, and no one uses Atom.  I know of at least one other IBM user of the assembler plugin, via the issues he opened.

Unless someone is interested in taking it over, normally I'd suggest moving the project to Emeritus state but nothing at the URL leads me to think that such a transition is even possible... which is puzzling.

**Comment by jmertic** [comment]
Hi @johnarwe !

Wanted to recap the discussion at the TAC on this topic.

- The TAC definitely appreciates all the work you've put into this project, and understands that you've had a change in role that takes you away from the day to day.
- The TAC thought it might be good for you to recruit a new maintainer, as they think the project is valuable and could be expanded to support other file formats. They suggested you send an email to the omp-techincal@lists.openmainframeproject.org list.
- If no interest comes up over the next month, then they would be fine with the recommendation to move it to Emertius status.

Let me know if this makes sense, or if you have any other questions or concerns.

**Comment by jmertic** [comment]
Looks like a new maintainer is interested - waiting on the confirmation note from @johnarwe and notes that the transition has happened...

https://lists.openmainframeproject.org/g/omp-technical/topic/soliciting_new_owner_for_omp/74924094

**Comment by jmertic** [comment]
@wlchurch is taking over as maintainer. I've added him as a maintainer on the repo, and invited him to the next TAC meeting to present and for the TAC to consider incubation renewal

**Comment by jmertic** [comment]
TAC approved renewal of incubation status on 20200806
