### ISSUE TITLE
New Project Proposal - Open Mainframe Education (name TBD)

### ISSUE THREAD

**Issue by gcartier94** [openmainframeproject/tac#109]
* Name of project (must be unique within OMP)

 Suggested names:
 Open Mainframe Education
 Open Mainframe Learning System 
 Mainframe Skills Solutions
 Open Education for Z

* Project description (what it does, why it is valuable, origin and history)

A project that aims to eliminate the roadblocks in mainframe education, by providing high-quality free education materials. 

We want to provide an easy to contribute platform that through the OMP will have a broad reach, the ability to scale, and offer quality and innovative curriculum as not everyone learns in the same way.

3 main points 
Reach, Scale, Quality

* Statement on alignment with OMP charter mission

This project aligns with all the mission topics, but is an expansion of the OMP to include the Mainframe Education Community. This is to invite new talent to the Mainframe Community.

Partner with the Mainframe community in order to increase the number of mainframe-focused educational programs and ease the path for anyone seeking  industry-relevant mainframe skills

* Sponsor from TAC (sponsor helps mentor projects)

We've discussed with the following TAC members:
Enyu Wang
Gregory MacKinnon
Robert Dahlberg

* Preferred maturity level (see [project stages](../../process/project_stages.md))

Incubation stage

* License and contribution guidelines (refer to the [OMP guidelines](contribution_guidelines.md))

Minimal license: Creative Commons
Other licensing needs will be discussed/defined at a later stage

* Source control (GitHub by default)

Github

* External dependencies (including licenses)

TBD (Internal discussion/process from IBM and Broadcom)

* Initial committers (how long working on project)

Guilherme Cartier (IBM)
Deborah Carbo (Broadcom)
Viviane de Padua (IBM)
Yvette LaMar (IBM)
John Mertic (OMP)
Lauren Valenti (Broadcom)

* Infrastructure requests (CI / OMP Cluster)

TBD, but probably no infrastructure request at this moment.

* Communication channels (slack, irc, mailing lists)

Slack channel 
#omp-education-project

* Issue tracker (GitHub by default)

Github

* Website

None yet

* Release methodology and mechanics

Basic methodology:
->Reviews to ensure accuracy
->Define submissions
->Define standards
But will require further planning

* Social media accounts

None yet

* Community size and any existing sponsorship

None yet

**Comment by paulnewt** [comment]
All things IBM Z, hw/sw, or is the plan to start with any specific IBM Z technical discipline, or TBD?

**Comment by jellypuno** [comment]
Will this be similar to the cobol course or interskill? Will it include OMP projects like Zowe Education?

**Comment by gcartier94** [comment]
Hi @paulnewt - The idea is to provide education for all things Z. But to start we will probably provide very fundamental materials for z/OS beginners.

Hi @jellypuno, at least at the beginning, the project will focus only on basic Mainframe concepts for new professionals. From that, we want to increasingly introduce more advanced concepts for more mature students. But the idea is not only to focus on the core Z technologies (ISPF, TSO, REXX, JCL, COBOL, etc..) but also educate on the new technologies as well like Zowe  :)

**Comment by paulnewt** [comment]
This is perfect - numerous participants in the OMP COBOL for beginners are repeatedly requesting z/OS skills beyond anything related to Enterprise COBOL such as GDG's, etc. etc.

**Comment by bobdahlberg** [comment]
We should provide an overall framework to organize the core Z technology curriculum by subject/topic modules.  This would create an outline of the areas we want to develop and flesh them out over time.

**Comment by paulnewt** [comment]
some idea's --- a bit dated now http://ibm.biz/zosintro

**Comment by solsu01** [comment]
I think elevating mainframe education/training to higher level is goodness. There's so much to learn about the Z platform, both on the application side and the IT administration side.

While there's already some good material on learning Z, it's all over the place and not well structured. If this project can take a structured approach in managing education targeting various subtopics on Z, I'm all for it!!

**Comment by bobdahlberg** [comment]
Sujay, I agree!  If we can get IBM's permission to look or even take their materials and map it to an outline of topics we can see where the state of Z education is at.   We can then start fleshing out what's lacking.

**Comment by gcartier94** [comment]
@solsu01 @bobdahlberg Since Mainframe skills can be quite intimidating for people that are just beginning, one of the approaches we are studying to go for is to create a roadmap of study topics, similar from whar this project have:
https://github.com/kamranahmedse/developer-roadmap

**Comment by solsu01** [comment]
I remember seeing the web developer roadmap on Reddit and was internally crafting a mainframe one in my head! This is awesome :)

**Comment by vipadua** [comment]
> some idea's --- a bit dated now http://ibm.biz/zosintro

The videos are under my favorite list! I really believe we should invest more and more in easy and simple videos to make Z consumable for the next generation

**Comment by bobdahlberg** [comment]
Agreed, it's really easy to do videos in PowerPoint use voice over slides and screen recordings.  Plus you can embed videos.  My students and I had to do a lot of this when the university had to go virtual in March and April.  Our university will be using a combination of virtual and classroom tools from now on.

**Comment by DeborahCarbo** [comment]
We intend to start this by providing existing assets already spread across our ecosystem today, we want MF vendors contributing content from what once was internal use only.   This of this as MF100 level courses.  This will lead to creation of new learning assets, a single source (vendor agnostic) combination of multiple contributors.  The outcome to the market is a clear pathway that will support any company, of any size, region or industry, to train new or retrain existing staff to take on mainframe job roles.  At no to low cost, but to also support (and not alienate) the many wonderful education companies out there who provide for fee services.

The vision is a single place to shop for MF foundations, with learning paths that make sense for a job role, Sys Prog, Security Admin, DBA, Operations, MF Application Developer, at some point the content will get more complex in the MF200 or MF300 level education, maybe there are vendor, services or product specific content branching that will occur.  The key is that we jointly contribute to the base, collaborate and advise the market on how to grow a mainframer in the hybrid datacenter.

**Comment by jmertic** [comment]
This was approved by the TAC on 2020-05-15.
