### ISSUE TITLE
New Project Proposal - GenevaERS

### ISSUE THREAD

**Issue by KipTwitchell** [openmainframeproject/tac#118]
*** Name of project** (must be unique within OMP)
GenevaERS, the Single-Pass Optimization Engine.

*** Project description** (what it does, why it is valuable, origin and history)

GenevaERS--the open source version of The IBM Scalable Architecture for Financial Reporting (SAFR)--is designed to deal with the problem of efficiently reporting on large volumes of transactional data. It is based on a set of software components with previously patented technology embedded, and it may be customized for use with new or existing data extraction and reporting applications.

GenevaERS is often used when large amounts of operational data reside in the z/OS® environment and complex reporting requirements create workloads that are difficult to manage through traditional techniques or tools.  GenevaERS:
- Runs quickly and efficiently
- Scales to deal with large volumes of detail data and table joins
- Creates multiple outputs, such as cubes, reports, and data marts
- Helps mitigate issues with reconciliation and restatement through a single view of the data
- Removes the need for additional transformations of the source data, allowing a simplified yet flexible and responsive data model
- Enables organizations to process data on the System z™ platform where it resides

The GenevaERS solution helps support key corporate decision-making. It has a proven track record of addressing real business problems, such as account activity analysis, product pricing, fraud detection, and multi-dimensional sales revenue analysis. It has also been used to enhance existing investments in large, packaged enterprise applications and extend their capabilities. It accomplishes this by executing highly tuned batch reporting workloads on IBM z/OS and System z.

*** Statement on alignment with OMP charter mission**

GenevaERS has a deep history on z/OS.  As a service offering (as opposed to a tool supported by license sales) built through collaboration with implementing partners, it has been developed in a collaborative way.  It fills a space neglected by other offerings.  The additional step of sponsorship by OMP will help with further adoption and development of the tool.

The closest technology might be Apache Spark; GenevaERS's native z/OS machine code generation provides much greater performance and distinct processing functionalities.

*** Sponsor from TAC** (sponsor helps mentor projects)
Enyu Wang, IBM, Program Director,  Ecosystem Business Development & Strategy

*** Preferred maturity level** (see [project stages](../../process/project_stages.md))
Incubation Stage

*** License and contribution guidelines** (refer to the [OMP guidelines](contribution_guidelines.md))
Apache 2.0

*** Source control** (GitHub by default)
TBD, likely GitHub.  Currently using Rational toolsets internally in IBM.

*** External dependencies** (including licenses)
No external licenses.  IBM certificate of originality in place, and all IBM approvals for contribution to open source secured.  Existing customers notified.  Current maintenance team all employed by IBM.

*** Initial committers** (how long working on project)
- Global Financial System SME: Kip Twitchell, continuous involvement for nearly 30 years
- Product Manager: James Hladyshewsky, manager for over 10 years, implementation consultant another 10 years 
- Lead architect Randall Ness, continuous involvement over 30 years

*** Infrastructure requests** (CI / OMP Cluster)
To be determined.  Source code currently maintained in Rational toolset internally within IBM.  

*** Communication channels** (slack, irc, mailing lists)
Slack channel named "sharealedger"  https://sharealedger.slack.com.
Active GenevaERS Alumni e-mail lists will be converted.

*** Issue tracker** (GitHub by default)
To be determined, currently using Rational toolset internally in IBM.

*** Website**
https://genevaers.org Additional thought leadership on shared ledgers will be developed within the https://sharealedger.org domain.

*** Release methodology and mechanics**
To be determined.   Currently use a permission access website for executable download by existing customers

*** Social media accounts**
Related blogging/vlogging performed by @finsysvlogger, Kip Twitchell, on twitter, linked-in, and at ledgerlearning.com (or financialsystemseducation.com) and on YouTube at Conversations with Kip (https://www.youtube.com/kiptwitchellvlog) and Sharealedger-org (https://www.youtube.com/channel/UCbogHQcugFgZK1QNoovNRHw)

*** Community size and any existing sponsorship**
IBM maintenance and knowledgeable staff on the order of a dozen people.  Currently approximately 25 - 30 GenevaERS/SAFR staff in Diaspora.  Two existing customers have various teams supporting the product, and extensible code which might be contributed to the project.  Growing community of Sharealedger participants over the last three months.

**Comment by KipTwitchell** [comment]
The SAFR solution will continue to be offered by IBM as a commercial version of GenevaERS with the addition that it will be zIIP processor enabled.  It will only be available to customers who have a maintenance contract for the product with IBM.  There are no other planned differences in the open source contribution.

**Comment by jmertic** [comment]
This was approved by the TAC on 2020-07-09.

@KipTwitchell - should I create new repo for the project? genevaers work?

**Comment by KipTwitchell** [comment]
Could use some counsel here.  I just looked at Zowe, and tell me if I"m wrong, but I see it as an organization, rather than just a single repro?  I wonder if, given the scale of the code base we have, we won't need more than one repro, and there is probably a little planning that needs to go into that, but we probably need a community repro immediately.  Thoughts?

**Comment by jmertic** [comment]
It might be good to understand the scope of code coming into the project to better understand things. I know you said it's internal in the process of open sourcing - perhaps you could showcase it to me somehow? We'll want to do a license scan anyways before it comes into a project managed repo.

**Comment by jmertic** [comment]
Working on onboarding now.
