### ISSUE TITLE
New Project Proposal - CBT TAPE

### ISSUE THREAD

**Issue by sbgolob** [openmainframeproject/tac#124]
* Name of project (must be unique within OMP)
CBT TAPE

* Project description (what it does, why it is valuable, origin and history)
Enormous repository of z/OS (and MVS) related code, tools, and modifications.  Has existed for 45 years.  This collection is being constantly and proactively expanded on a continuous basis, to keep up with IBM system changes and user code improvements.

* Statement on alignment with OMP charter mission
Supporting almost all z/OS installations in the world, and encouraging learning among systems programming practitioners, new and old alike.  Supporting z/OS in a great many companies and other installations worldwide, keeping their expenses lower and greatly aiding in their system support.  Adding enormously to the value of z/OS for all z/OS installations, over a very long period of time.

* Sponsor from TAC (sponsor helps mentor projects)

* Preferred maturity level (see [project stages](../../process/project_stages.md))
Ongoing, for as long as possible.  This product supports all z/OS installations worldwide, and also MVS-based systems which are older.

* License and contribution guidelines (refer to the [OMP guidelines](contribution_guidelines.md))
All contributions have to be usable by anybody, for no cost.  Some contributors maintain ownership by means of a copyright notice, but they must allow anyone to use their materials as submitted to the collection.  There are no "timeouts" allowed for software in this collection.

* Source control (GitHub by default)
www.cbttape.org web site

* External dependencies (including licenses)
Support for this project needs one or more z/OS LPARs. No additional licenses required.

* Initial committers (how long working on project)
Sam Golob (30 years).  Sam Knutson (22 years).  Sam Knutson pays for the website.  Sam Golob controls contents of the collection.

* Infrastructure requests (CI / OMP Cluster)

* Communication channels (slack, irc, mailing lists)
www.cbttape.org

* Issue tracker (GitHub by default)
www.cbttape.org website.  emails to sbgolob@cbttape.org are the main input for site maintenance.

* Website
www.cbttape.org

* Release methodology and mechanics
Download from www.cbttape.org

* Social media accounts
None currently.  The word-of-mouth knowledge of this project (the CBT Tape) is known by most z/OS and MVS-based systems support practitioners all over the world. 

* Community size and any existing sponsorship
At least 3000 or more installations use the service

**Comment by jmertic** [comment]
Project accepted during the meeting.
