### ISSUE TITLE
Ambitus incubation renewal

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#130]
@jbostian Please be prepared to present updates on the project and seeking of Incubation renewal or graduation to Active state.

**Comment by jbostian** [comment]
Here are some statistics to summarize our activity over the last year.  If we can continue incubation over the next year, I think we should make good progress towards graduation.

Stats
- 12 team members - mostly from Rocket & IBM 
- 6 contributors
- 7 repos
- Met regularly bi-weekly over the last year - 19 TSC meetings
- 26 members in the ambitus-discussion group
- 29 members in the #ambitus slack channel

3 primary activities
- Host porting activities for 4 efforts - gcc, glibc, binutils, ztron
- zos-native - examples, and how-to info for people new to the platform, or to open source
- linux-containers - how-to and example information for several containerized workloads
   Several image examples in the pipeline
   - 15-20 views/day, ~5 unique visitors/day, last 2 weeks

ambitus - the top-level project repo
- 15-20 views/day, ~3 unique visitors/day, last 2 weeks

**Comment by jmertic** [comment]
Incubation extension approved. See attached email votes.

[The Linux Foundation Mail - VOTE_ Approve incubation renewal for Ambitus.pdf](https://github.com/openmainframeproject/tac/files/5438847/The.Linux.Foundation.Mail.-.VOTE_.Approve.incubation.renewal.for.Ambitus.pdf)
