### ISSUE TITLE
New Project Proposal - Tessia

### ISSUE THREAD

**Issue by machikhin** [openmainframeproject/tac#132]
* Name of project (must be unique within OMP)

Tessia

* Project description (what it does, why it is valuable, origin and history)

Tessia aims to automate and simplify installation/configuration/management/testing of Linux systems running on the IBM Z platform.

* Statement on alignment with OMP charter mission

Tessia is built to support Linux installation on the Mainframe and lifecycle management of LPAR/zVM/KVM Linux instances. It knows about Mainframe specific devices and can handle them. 

* Sponsor from TAC (sponsor helps mentor projects)

Ingo Adlung

* Preferred maturity level (see [project stages](../../process/project_stages.md))

Incubation Stage

* License and contribution guidelines (refer to the [OMP guidelines](contribution_guidelines.md))

Apache 2.0

* Source control (GitHub by default)

GitLab: https://gitlab.com/tessia-project/tessia
GitHub (as mirror): https://github.com/tessia-project/tessia

* External dependencies (including licenses)

psycopg2 (BSD-like license)
SQLAlchemy (MIT License) 
alembic (MIT License)
PyYAML (MIT License) 
jsonschema (MIT License) 
ldap3 (LGPLv3)
flask (BSD License)
Flask-SQLAlchemy  (BSD License)
flask-potion (MIT License) 
jinja2 (BSD License)
ansible (LGPLv3)
requests (Apache 2.0 License)
docker (Docker's open source components are generally licensed under the Apache 2.0 License)
click (BSD License)
tokio (MIT License)
Redis (three clause BSD license)
PostgreSQL ( PostgreSQL License,, a liberal Open Source license, similar to the BSD or MIT licenses)

* Initial committers (how long working on project)

Paulo de Rezende Pinatti ( first commit was done 28 Jun, 2016)
Alexey Machikhin
Alexander Efremkin

* Infrastructure requests (CI / OMP Cluster)

None at the moment

* Communication channels (slack, irc, mailing lists)

 IRC at the #tessia channel on OFTC

* Issue tracker (GitHub by default)

GitLab: https://gitlab.com/tessia-project/tessia/-/issues
GitHub (as mirror):  https://github.com/tessia-project/tessia/issues

* Website

None at the moment

* Release methodology and mechanics

Rolling releases
CI/CD based on GitLab mechanics

* Social media accounts

None at the moment

* Community size and any existing sponsorship

IBM supports active development on it
about 200 active users (since January 2018)

**Comment by jmertic** [comment]
Thank you @machikhin - looking forward to the presentation at today's TAC meeting. I've added you to the invite now.

**Comment by machikhin** [comment]
Thank you @jmertic , me too )

Today's presentation: [tessia_TAC_Meeting.pdf](https://github.com/openmainframeproject/tac/files/5349289/tessia_TAC_Meeting.pdf)

Link to previous presentation (Open Mainframe Summit): https://www.youtube.com/watch?v=_4Uk0pXAhig&list=PL8REpLGaY9QGExAKP21tQ7v952Ri6re9p&index=12

**Comment by jmertic** [comment]
Project accepted by TAC - email votes attached.

[The Linux Foundation Mail - VOTE_ Approve Tessia as an incubation project.pdf](https://github.com/openmainframeproject/tac/files/5438841/The.Linux.Foundation.Mail.-.VOTE_.Approve.Tessia.as.an.incubation.project.pdf)
