### ISSUE TITLE
Debian s390x support

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#140]
FYI, there’s a serious risk that the Debian Linux community will stop distributing a s390x architecture build of their operating system. The community is soliciting responses from willing maintainers for each architecture per this roll call announcement:

https://lists.debian.org/debian-s390/2020/11/msg00000.html

Philipp Kern posted a follow up warning here:
https://lists.debian.org/debian-s390/2020/11/msg00001.html

**Comment by markkp** [comment]
On 11/10/20 8:29 AM, John Mertic wrote:
> FYI, there’s a serious risk that the Debian Linux community will stop
> distributing a s390x architecture build of their operating system. The
> community is soliciting responses from willing maintainers for each
> architecture per this roll call announcement:
> 
> https://lists.debian.org/debian-s390/2020/11/msg00000.html
> 
> Philipp Kern posted a follow up warning here:
> https://lists.debian.org/debian-s390/2020/11/msg00001.html

I see they're talking about not being able to get access to mainframe
hardware. Has anyone told them about the LinuxONE Community Cloud?


Mark Post

**Comment by jmertic** [comment]
They use that infrastructure already AFAIK.

Thank you,

John Mertic
Director of Program Management - Linux Foundation
ASWF, LF AI and Data, LF Energy and Open Mainframe Project
jmertic@linuxfoundation.org
+1 234-738-4571

**Comment by jmertic** [comment]
Follow up is set up a call with Phillip to learn more

**Comment by jmertic** [comment]
Meeting held and working group proposal created at #222.
