### ISSUE TITLE
Ambassador application - Joe Bostian

### ISSUE THREAD

**Issue by jbostian** [openmainframeproject/tac#144]
Thank you for your interest in becoming an Open Mainframe Ambassador. To be considered, please answer the following questions. Please also reference the [Ambassador Program overview](https://github.com/openmainframeproject/tac/blob/master/process/ambassadors.md) for any questions.

* Your name ( also put in the title replacing NAME )
Joe Bostian

* Email
jbostian@us.ibm.com

* Bio
I have spent my career working at the top layers of the platform stack, supporting Unix and Linux based workloads on z/OS.  Open source software has matured into the de facto platform for new workloads across operating systems, and I am an enthusiastic supporter of this development.  

* Projects within OMP you would want to be an ambassador for
Ambitus, Software Discovery Tool

* Why do you want to be an ambassador?
The future of the mainframe is bound to our ability to make it an open accepted platform, and I want to help make that happen.

**Comment by jmertic** [comment]
Thank you! Can you also...

- Attach a headshot?
- List any other topics you would be able to speak about?

**Comment by jbostian** [comment]
FYI - Photo for Ambassador project.  I don't have any other topics to speak about aside from the ones I'm involved in during the recular TAC meetings.
__________________________________________________________________________________________
 
                                                                        Kind Regards / Mit freundlichen Grüßen / Cordialmente
                        jbostian@us.ibm.com   (Joe)                        IBM z Systems, Open Source and Analytics Architect                                                                        
 
 
----- Original message -----From: John Mertic <notifications@github.com>To: openmainframeproject/tac <tac@noreply.github.com>Cc: Joe Bostian <jbostian@us.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [openmainframeproject/tac] Ambassador application - Joe Bostian (#144)Date: Wed, Dec 9, 2020 12:16 PM 
 
Thank you! Can you also...
        Attach a headshot?        List any other topics you would be able to speak about?

**Comment by jmertic** [comment]
Your application has been approved - next steps for the announcement at https://github.com/openmainframeproject/foundation/issues/167
