### ISSUE TITLE
Ambassador application - Matt Hogstrom

### ISSUE THREAD

**Issue by hogstrom** [openmainframeproject/tac#145]
Thank you for your interest in becoming an Open Mainframe Ambassador. To be considered, please answer the following questions. Please also reference the [Ambassador Program overview](https://github.com/openmainframeproject/tac/blob/master/process/ambassadors.md) for any questions.

* Your name ( also put in the title replacing NAME )
Matt Hogstrom

* Email
matt@hogstrom.org

* Bio
Long time mainframer have been a customer as well as a creator of mainframe software working for IBM and Broadcom.  One of the original comitters to the Zowe project and helped the formation of Zowe at the Open Mainframe Project.

* Projects within OMP you would want to be an ambassador for
Zowe, TSC

* Why do you want to be an ambassador?
I continue to develop code for Zowe and collaborating in the community as well as monitoring and participating as an interested party in the Technical Steering Comittee.

**Comment by jmertic** [comment]
Thank you! Can you also...

- Attach a headshot?
- List any other topics you would be able to speak about?

**Comment by hogstrom** [comment]
![me_cartoonFilter-1136x640](https://user-images.githubusercontent.com/2906023/101674435-7d487180-3a26-11eb-8248-036f10df85aa.jpg)

**Comment by jmertic** [comment]
Your application has been approved - next steps for the announcement at https://github.com/openmainframeproject/foundation/issues/167

**Comment by jmertic** [comment]
Your application has been approved - next steps for the announcement at https://github.com/openmainframeproject/foundation/issues/167
