### ISSUE TITLE
Open z/OS Enrollment WG approval

### ISSUE THREAD

**Issue by KipTwitchell** [openmainframeproject/tac#148]
I propose we consider forming a new Open Source community dedicated to building tools and configuration enabling such an environment for those willing to dedicate both hardware and scarce z/OS system programmer resources to such an effort.  
 
I suggest we have a discussion about this idea on the next OMP TAC meeting, this coming Thursday.  I solicit your feedback to refine the proposal.
 
**Problem Statement**: The GenevaERS OMP Project gives a good example of the impediments experienced exploring z/OS, and developing new Open Source solutions.  The historically very well controlled z/OS environments, typically only available to users within some formally defined organization, works against the need to allow new team members, new configuration, evolving requirements required for an open source community.  
 
This need goes beyond just open source communities; existing z/OS consultants need similar capabilities to explore new software configurations, develop exploratory training capabilities and integration approaches to solve new problems, and make recommendations to existing customers.  Those new to the environment have similar needs.  
 
Various organizations today have offered z/OS resources for open source communities.  One senses that a key resource in these efforts is system programmer time.  In the aging resource market for z/OS skills, system programmers are a much smaller set.  But these resources are at the center of what is needed to enable many aspects of the above.
 
**Preliminary Vision**:  Fundamentally, hardware capable of running z/OS is needed.  This effort would not target that need, but recognizes that there are some organizations willing to dedicate some capacity to these efforts.  If dedicating resources were easier while continuing to be highly controlled, more may be willing to do so.
 
What if organizations had the ability to download tools and configuration to automate a z/OS public cloud offering.  They would want to be able to control, for example:
 - Classes of users, by geography or other measures
 - What software might be installed
 - The types and numbers of lpars 
 - When the system would be available 
 
**Next Steps**:  I recommend a discussion at the December OPM Technical Advisor Committee (TAC) meeting about this proposal, to consider forming an exploratory committee for a new OMP project, bringing together parties that have a sense of:
(1) the needs for system programmer automation, to enable the above
(2) Interests and concerns of owners of Z hardware who might be willing to consider assisting in this space
(3) knowledge of IBM z/OS cloud initiatives and how this effort might be complementary
(4) Actual OMP project experiences to date.

**Comment by jmertic** [comment]
@KipTwitchell to lead the formation of a working group that would define a project proposal. @jmertic to help coordinate the meetings.

3/15/96 - prediction of last mainframe being turned off - timing for announcement on 25th anniversary.

**Comment by jmertic** [comment]
Please provide your availability to join this working group kickoff call at https://doodle.com/poll/a7df7m7eyxs729z5?utm_source=poll&utm_medium=link by EOD Friday, November 11, 2020

**Comment by jmertic** [comment]
Plan is to approve the group charter at the 2/11 TAC meeting per @KipTwitchell

**Comment by jmertic** [comment]
Working group approved during the TAC meeting on 2/10
