### ISSUE TITLE
Demo using Polycephaly in different developer scenarios

### ISSUE THREAD

**Issue by edge05** [openmainframeproject/tac#149]
The TAC is always looking for topics of interest to the community. Please fill out the following details and this will be added to the next TAC meeting agenda.

* Topic to be discussed ( make this the title of the issue )
 - I would like to demonstrate the power of Polycephaly under different development situations and how Polycephaly can not only save time, but z/OS resources
* Details or background
- Polycephaly is working on the new infrastructure and I would like to demo the project to the committee
* Actions or feedback from the TAC

Please also note you must be available to lead this discussion on a TAC meeting. Calendar of TAC meetings is at https://lists.openmainframeproject.org/g/omp-technical/calendar.

**Comment by jmertic** [comment]
Closing - done at previous TAC meeting
