### ISSUE TITLE
Ambassador application - Dan Kelosky

### ISSUE THREAD

**Issue by dkelosky** [openmainframeproject/tac#151]
Thank you for your interest in becoming an Open Mainframe Ambassador. To be considered, please answer the following questions. Please also reference the [Ambassador Program overview](https://github.com/openmainframeproject/tac/blob/master/process/ambassadors.md) for any questions.

* Your name ( also put in the title replacing NAME )
Dan Kelosky

* Email
daniel.kelosky@broadcom.com

* Bio
Likes programming/automation in mainframe (assembler, C/C++), distributed (Node.js), and web development (Firebase, Angular).

* Projects within OMP you would want to be an ambassador for
Zowe

* List any other topics you would be able to speak about
Mainframe software development, Node.js, TypeScript, HLASM, Metal C, VS Code Extension Development

* Why do you want to be an ambassador?
I try to be one already through [medium posts](https://medium.com/@dkelosky), [LinkedIn](https://www.linkedin.com/in/dkelosky/), [SHARE participation](https://www.share.org/blog/use-zowe-to-broaden-assembler-development-practices), and [coding within Zowe](https://github.com/zowe/zowe-cli/commits?author=dkelosky).

* Attach a headshot
![image](https://user-images.githubusercontent.com/14940561/101909431-78e99900-3b8b-11eb-96d7-3d246eb92576.png)

**Comment by jmertic** [comment]
Thank you! Can you also...

- Attach a headshot?
- List any other topics you would be able to speak about?

**Comment by dkelosky** [comment]
@jmertic - my submission is updated with the info you requested.

**Comment by jmertic** [comment]
Your application has been approved - next steps for the announcement at https://github.com/openmainframeproject/foundation/issues/167
