### ISSUE TITLE
Ambassador application - Jessielaine Punongbayan

### ISSUE THREAD

**Issue by jellypuno** [openmainframeproject/tac#152]
Thank you for your interest in becoming an Open Mainframe Ambassador. To be considered, please answer the following questions. Please also reference the [Ambassador Program overview](https://github.com/openmainframeproject/tac/blob/master/process/ambassadors.md) for any questions.

* Your name ( also put in the title replacing NAME )
Jessielaine Punongbayan

* Email
jessielaine.punongbayan@broadcom.com

* Bio
I am a Modern Mainframer who has experience in mainframe programming and as well as the distributed side. I am passionate in finding new solutions to modernize mainframe and as well share it with the community. I am a committer for Zowe Explorer, Zowe CLI and Zowe Mobile Application. I am part of the TSC for OMP Cobol Programming Course and a member of the Cobol Working Group.

* Projects within OMP you would want to be an ambassador for
Zowe and Cobol Programming Course

* Why do you want to be an ambassador?
I want to continuously share my knowledge about mainframe and Zowe in our community. I do this through the following channels: [Medium](https://medium.com/@jessielaine.punongbayan), [Youtube](https://www.youtube.com/channel/UCZrvxFwT1GpvJuFRyqc5uWg), [Twitter](https://twitter.com/jellpunongbayan?lang=en), [Linkedin
](https://www.linkedin.com/in/jessielaine-punongbayan-59320464/), Different Conferences such as [GSE](https://conferences.gse.org.uk/2019/agenda/presentation/1741), IDUG EMEA, [Open Mainframe Summit](https://oms2020.sched.com/speaker/jessielainepunongbayan?iframe=no&w=100%&sidebar=yes&bg=no), Broadcom's MTE, [Webinars](https://youtu.be/bBifcaQltkI) and Podcasts ([I am a Mainframer](https://www.openmainframeproject.org/blog/2020/08/11/i-am-a-mainframer-jessielaine-jelly-punongbayan), [TFiR](https://www.tfir.io/meet-the-2020-zowe-hackathon-winners-open-mainframe-summit/) and [Terminal Talk](https://podcasts.apple.com/us/podcast/jessielaine-punongbayan-cobol-and-zowe/id1246775230?i=1000488694275))

**Comment by jmertic** [comment]
Thank you! Can you also...

- Attach a headshot?
- List any other topics you would be able to speak about?

**Comment by jellypuno** [comment]
@jmertic Sure.

- Headshot
![Headshot](https://user-images.githubusercontent.com/45042840/101663625-3b7df200-3a4b-11eb-896c-69a09194cd61.jpg)

- Topics to talk about: Anything Mainframe related (COBOL Programming, A little bit of SysAdmin), Zowe related topics (Zowe Explorer, Zowe CLI etc), Integrating Open Source Tools to mainframe through CI/CD, Automated tests, web and mobile apps.

**Comment by jmertic** [comment]
Your application has been approved - next steps for the announcement at https://github.com/openmainframeproject/foundation/issues/167
