### ISSUE TITLE
Ambassador application - Richelle Craw

### ISSUE THREAD

**Issue by crawr** [openmainframeproject/tac#153]
Thank you for your interest in becoming an Open Mainframe Ambassador. To be considered, please answer the following questions. Please also reference the [Ambassador Program overview](https://github.com/openmainframeproject/tac/blob/master/process/ambassadors.md) for any questions.

* Your name ( also put in the title replacing NAME )
Richelle Craw

* Email
richelleanne.craw@broadcom.com

* Bio
I am a mainframer, COBOL developer, Zowe committer and Zowe Explorer Squad member. I develop new solutions for modern mainframers, including software provisioning via z/OSMF, Zowe CLI, Zowe Explorer, and the Zowe Mobile Application.  

* Projects within OMP you would want to be an ambassador for
Zowe

* Why do you want to be an ambassador?
I enjoy continuous learning and I try to share what I know by writing [blogs](https://www.idug.org/browse/blogs/blogviewer?BlogKey=22f9b8b4-4645-4c50-ba31-2d1140025544), participating in Zowe [hackathons](https://medium.com/zowe/zowe-on-the-go-a-mobile-application-for-modern-mainframers-6f4eb849ff57), presenting in conferences ([GSE UK](https://conferences.gse.org.uk/2019/agenda/presentation/1741), [Open Mainframe Summit](https://oms2020.sched.com/speaker/richelleanne.craw), Broadcom MTE, IDUG EMEA), and talking about Zowe in [interviews](https://www.tfir.io/meet-the-2020-zowe-hackathon-winners-open-mainframe-summit/).

**Comment by jmertic** [comment]
Thank you! Can you also attach a headshot?

**Comment by jmertic** [comment]
And in addition, are there other topics you would be able to speak about?

**Comment by jmertic** [comment]
Your application has been approved - next steps for the announcement at https://github.com/openmainframeproject/foundation/issues/167

**Comment by crawr** [comment]
Headshot
<img src="https://user-images.githubusercontent.com/45845502/105689172-b6677300-5efa-11eb-8011-c3872f7312b7.png" width="300" height="400">
