### ISSUE TITLE
Ambassador application - Greg MacKinnon

### ISSUE THREAD

**Issue by gmackinnon** [openmainframeproject/tac#158]
Thank you for your interest in becoming an Open Mainframe Ambassador. To be considered, please answer the following questions. Please also reference the [Ambassador Program overview](https://github.com/openmainframeproject/tac/blob/master/process/ambassadors.md) for any questions.

* Your name ( also put in the title replacing NAME )
Greg MacKinnon

* Email
gregory.mackinnon@broadcom.com

* Bio
 Greg is a solution architect working on Open Mainframe technologies at Broadcom, which includes both CA Brightside and Zowe open source efforts. Greg has experience spanning both the mainframe and distributed worlds. Over the past several years, he's worked on various projects to modernize and open up the mainframe. The most recent of these is Zowe. As part of the CA Technologies team that first joined Zowe (zlux then), he drove getting the API Mediation Layer accepted and contributed to the open source initiative. 

* Projects within OMP you would want to be an ambassador for
Zowe

* List any other topics you would be able to speak about
APIs, mainframe modernization, mainframe and cloud native technologies

* Why do you want to be an ambassador?
Opening up the mainframe so that it can be accessed and interacted with like any other platform (via CLIs, APIs, cloud integrations etc) is essential to its future.  OMP and its ambassador program can help foster and champion this cause. 

* Attach a headshot

**Comment by gmackinnon** [comment]
![bio-image](https://user-images.githubusercontent.com/35381000/101806690-4768c300-3ae2-11eb-96e1-cf8d5065b3c6.jpg)

**Comment by jmertic** [comment]
Your application has been approved - next steps for the announcement at https://github.com/openmainframeproject/foundation/issues/167
