### ISSUE TITLE
Jerry Edgington

### ISSUE THREAD

**Issue by edge05** [openmainframeproject/tac#160]
Thank you for your interest in becoming an Open Mainframe Ambassador. To be considered, please answer the following questions. Please also reference the [Ambassador Program overview](https://github.com/openmainframeproject/tac/blob/master/process/ambassadors.md) for any questions.

* Your name ( also put in the title replacing NAME )
Jerry Edgington, Senior Technical Analyst

* Email
Jerry.Edgington@WesternSouthern.com

* Bio
I have 35+ years of zSeries system programming experience, including z/OS, z/VM, and Linux on Z

* Projects within OMP you would want to be an ambassador for
Any of the projects, including Polycephaly

* List any other topics you would be able to speak about
Open Source, most anything about z/OS

* Why do you want to be an ambassador?
Since I am the primary developer and supporter for Polycephaly, I think this is a natural extension to help promote OMP's projects, including my own

* Attach a headshot

**Comment by jmertic** [comment]
Your application has been approved - next steps for the announcement at https://github.com/openmainframeproject/foundation/issues/167

**Comment by jmertic** [comment]
@edge05 - Can you provide a headshot?
