### ISSUE TITLE
Ambassador application - Joe Winchester

### ISSUE THREAD

**Issue by Joe-Winchester** [openmainframeproject/tac#163]
Thank you for your interest in becoming an Open Mainframe Ambassador. To be considered, please answer the following questions. Please also reference the [Ambassador Program overview](https://github.com/openmainframeproject/tac/blob/master/process/ambassadors.md) for any questions.

* Your name ( also put in the title replacing NAME )
Joe Winchester

* Email
winchest@uk.ibm.com       (also  JoeWinchester@gmail.com)

* Bio
I am a senior technical staff member in the IBM Systems division working on Project Zowe. I am part of the Zowe Leadership Committee and the IBM Zowe architect, having been involved with Zowe since its inception where I remain an active contributor and committer. As part of the Zowe onboraders squad I have presented on Zowe at a number of conferences, both in-person and virtual, ranging from open source summit, Share, Z Tech University, Guide Share meetups, Open Mainframe Summit, and more.  As well these larger conferences I also present 1:1 with customers as well as more intimate smaller user group meetups, for example in 2020 during the pandemic I presented on Zowe at virtual user group meetups spanning Australia, Turkey, China, France, and Denmark. I have always enjoyed open source tools and prior to working on Zowe I was a committer and team lead of the Eclipse.org open source Data Bindings and Visual Editor project as well as IBM's commercial Eclipse mainframe platform the  IBM z/OS Explorer Aqua.  Prior to Eclipse I worked on Java Standard Edition where I was IBM's representative on the Java community process and helped to create a number of open source Java specification requests.

* Projects within OMP you would want to be an ambassador for
Zowe

* List any other topics you would be able to speak about
Mainframe modernization
Open Source

* Why do you want to be an ambassador?
I love open source projects and I believe they are having a very transformative effect on helping modernize the mainframe by pulling together ISVs, customers old and new, as well as mainframers old and new. Project Zowe excites me as it's making progress in areas that previous attempt failed and I believe it has a great future ahead of it for open source and the z platform and its customers. 

* Attach a headshot
![image](https://user-images.githubusercontent.com/28100302/102080620-adb55480-3e06-11eb-9780-d528e2d6f3a0.png)

**Comment by jmertic** [comment]
Your application has been approved - next steps for the announcement at https://github.com/openmainframeproject/foundation/issues/167

**Comment by Joe-Winchester** [comment]
Thank you @jmertic.  Let me know what I can do as an ambassador to help make 2021 a great year for mainframe and open source tools and projects.
