### ISSUE TITLE
Ambassador application - Rose Sakach

### ISSUE THREAD

**Issue by RASakach** [openmainframeproject/tac#166]
Thank you for your interest in becoming an Open Mainframe Ambassador. To be considered, please answer the following questions. Please also reference the [Ambassador Program overview](https://github.com/openmainframeproject/tac/blob/master/process/ambassadors.md) for any questions.

* Your name ( also put in the title replacing NAME )
* _Rose Sakach_

* Email
* _Rose.Sakach@broadcom.com_

* Bio
* _Rose is a Global Product Manager at Broadcom responsible for Zowe CLI, Zowe Support and solutions that integrate mainframe developers with modern tooling and enable DevOps for the Enterprise. She has lead sessions at SHARE, CA World, DevOps.com, and various worldwide Broadcom Product User Groups. She has over 30 years of experience in technology roles including application development, systems programming, operations, product administration, consulting services and product management._

* Projects within OMP you would want to be an ambassador for
* Zowe

* List any other topics you would be able to speak about
_* Zowe Conformance
* Zowe LTS
* Zowe Components
* Zowe Onboarding
* COBOL, Modern Mainframe Development_

* Why do you want to be an ambassador?
I've spent my entire career (more than 3 decades) as an I.T. professional working with mainframes and remain very passionate about this platform despite the rumors or its impending demise.  The introduction of Zowe - the first EVER Open Mainframe Project for z/OS gave all Mainframers an opportunity to become a part of a greater community while making history.  As a Zowe Ambassador I'd love the opportunity to help all I.T. professionals understand the importance of the platform, how it has continually transformed to meet the needs of customers, demystify any concerns associated with "Open Source" and welcome them to the project.

* Attach a headshot
* 
![RoseSakach++](https://user-images.githubusercontent.com/42411859/102415376-0da62980-3fc6-11eb-9af1-9a83605195d2.png)

**Comment by jmertic** [comment]
Your application has been approved - next steps for the announcement at https://github.com/openmainframeproject/foundation/issues/167
