### ISSUE TITLE
Project proposal: consolez

### ISSUE THREAD

**Issue by mike99mac** [openmainframeproject/tac#169]
* Name of project (must be unique within OMP)
consolez

* Project description (what it does, why it is valuable, origin and history)
It allows z/VM console access and CP command invocation through a Web user interface

* Statement on alignment with OMP charter mission
It is open source and furthers z/VM and zLinux usability.

* Sponsor from TAC (sponsor helps mentor projects)
Not sure

* Preferred maturity level (see [project stages](../../process/project_stages.md))
Even though it's less than a month old, it's mostly complete in my book.  I added a search function, wrote a short document, now tied to 'Help' buttons and created an RPM.  The code is up on github.com (but there are still some issues).

* License and contribution guidelines (refer to the [OMP guidelines](contribution_guidelines.md))
Artistic 2.0

* Source control (GitHub by default)
https://github.com/mike99mac/consolez

* External dependencies (including licenses)
Need z/VM, zLinux, Apache and other related Linux RPMs, but that's all

* Initial committers (how long working on project)
About a month

* Infrastructure requests (CI / OMP Cluster)
It would be nice to have a couple of zLinux IDs to set up a reference platform.  Also one that has access to the Internet (I do not) 

* Communication channels (slack, irc, mailing lists)
IBMVM, linux-390 mailing lists.  Could start another channel if there's a hope for any activity.

* Issue tracker (GitHub by default)

* Website
For now my Google Sites page: https://sites.google.com/site/mike99mac/home
I see this as taking a back seat to the github site.

* Release methodology and mechanics
Release early, release often :))

* Social media accounts
There's a 14 minute youtube video and post on Linked-in.  I have been banished from Facebook, but no great loss

* Community size and any existing sponsorship
Not sure

**Comment by jmertic** [comment]
This project was approved by the TAC today. Next steps at https://github.com/openmainframeproject/foundation/issues/163
