### ISSUE TITLE
Steven Dickens

### ISSUE THREAD

**Issue by StevenDickens** [openmainframeproject/tac#182]
Thank you for your interest in becoming an Open Mainframe Ambassador. To be considered, please answer the following questions. Please also reference the [Ambassador Program overview](https://github.com/openmainframeproject/tac/blob/master/process/ambassadors.md) for any questions.

* Your name ( also put in the title replacing NAME ) Steven Dickens

* Email Steven Dickens

* Bio: Steven is an IBMer responsible for global sales of IBM’s premier Linux and Open Source server platform, LinuxONE. In this role he advocates, evangelises and champions the adoption of LinuxONE in the Cloud, Managed Service Provider, Linux and Open Source market segments. Steven has spent 20-years plus in the Information Technology industry, with considerable experience in both hardware and software platforms with senior roles in: Offering Management, Marketing Specialist Sales and Client Management for organisations such as CA (now Broadcom), HP and latterly IBM.
Steven was a founding board member, former Chairperson and am now the Chairperson of the Marketing Committee for the Open Mainframe Project, a Linux Foundation Collaborative Project promoting Linux and Open Source on the mainframe – www.openmainframeproject.org
Steven is an avid supporter of using social media tools to increase customer engagement and has spoken at Social Media conferences on the subject of Social Media advocacy.  Steven uses numerous social platforms to further awareness of IBM’s LinuxONE offerings and he is also the editor of the www.mainframedebate.com 

* Projects within OMP you would want to be an ambassador for: Everything

* List any other topics you would be able to speak about

* Why do you want to be an ambassador? Because I host the I am a Mainframe podcast and I started OMP!

* Attach a headshot

**Comment by jmertic** [comment]
Congratulations! You have been accepted as an Open Mainframe Project Ambassador. Look to your email for the next steps.
