### ISSUE TITLE
Graduation review - COBOL Programming Course

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#188]
Up for renewal on 4/9/2021

**Comment by jmertic** [comment]
@Sudharsana-Srinivasan is planning to present a proposal for Graduation. Please submit to the TAC by EOD tomorrow if possible.

**Comment by Sudharsana-Srinivasan** [comment]
TAC - COBOL Programming Course Graduation presentation
[OMP COBOL Course - Active Stage.pptx](https://github.com/openmainframeproject/tac/files/6247137/OMP.COBOL.Course.-.Active.Stage.pptx)

**Comment by jmertic** [comment]
This was approved by the TAC during the 20210408 meeting - congratulations!

**Comment by jmertic** [comment]
Next steps at https://github.com/openmainframeproject/foundation/issues/188
