### ISSUE TITLE
Update voting TAC members

### ISSUE THREAD

**Issue by jperezpbos** [openmainframeproject/tac#212]
Please add Javier Perez as a new appointed TAC voting representative from IBM. A replacement for Enyu Wang.

Updates in https://tac.openmainframeproject.org/  and  https://www.openmainframeproject.org/about/tac possible other locations.

**Comment by jmertic** [comment]
Set to rollout overnight - please confirm tomorrow and close if it all looks right

**Comment by jperezpbos** [comment]
Updated,  thanks
