### ISSUE TITLE
Discuss badging for projects

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#265]
Currently we have some badges, discussion here would be to review and look at more opportunities 

https://www.credly.com/organizations/the-linux-foundation/collections/open-mainframe-project/badge_templates

**Comment by KipTwitchell** [comment]
The GenevaERS project determined that we wanted to issue a badge for GenevaERS committers, to reward committers for their work on the project.

**Comment by jmertic** [comment]
Thanks @KipTwitchell - I've made a LF CS request for the design. Will follow up directly with you and the project when we have a concept.

**Comment by jmertic** [comment]
Close this - will add to the project benefits list.

**Comment by jmertic** [comment]
[Add Credly badges as a benefit for projects and working groups](https://github.com/openmainframeproject/tac/commit/1870a9120dcba69d51a4645fee3bddba4a762f36)
…
