### ISSUE TITLE
Discuss 2022 Goals and Objectives

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#300]
### Please share any additional details on this topic

Review deck at https://github.com/openmainframeproject/foundation/blob/main/goals/2022.pdf

### Detail what actions or feedback you would like from the TAC

TAC to discuss and strategize on how it can impact these goals and objectives.

**Comment by KipTwitchell** [comment]
I agree with many comments on the meeting that IT architect buy-in is a challenge.  I think perhaps a more simple place to start in developing that message is to start with the 20 endorsed users for projects:  What would they gain by doing that?  How one approaches companies to give those endorsement is a foundation for the messaging on other larger issues.

**Comment by Joe-Winchester** [comment]
Great deck @jmertic ,  a few comments I have reading through the slides:
- 5 year plan, align 2020 focuses.  Currently the OMP projects seem to be tooling focused,  there are quite a lot of open source languages (Java, Node.js, GoLang, ....) that are important to mainframe customer's modernization story.  Node.js is an LF runtime, maybe OMP can work alongside them ?  OMP has a great story around COBOL through its working group and training course, but other languages are available and I'd like to see a broader focus to recognize diversity.
- As a goal I always look at the other LF projects like k8s, Helm, Jenkins, Node-Red, ...   Can a target be set to reach out to these projects at all levels, get mainframe accreditation, get presenters at their conferences, get mention on their FAQs and docs to point mainframe users towards OMP, ...   
- What does "3 new Zowe impact/scope projects active at the OMP" mean ?
- Focus Personas:  I love this as an idea to move OMP forward, not sure that "Polycephany" should be listed as Jenkins CI/CD.  "Polycephany" has a pre-req on an IBM priced tool (Depdendency Based Build aka DBB). Promoting this would be no different to having an OMP project for CA Endeavor or Compuware Topaz script collaboration, both of which are great non-open source vendor specific products.
Polycephany's last commit was 4 months ago, its last build was October 2020 and it has had just 10 issues raised against the project (all by Jerry who is the project lead).  Very happy to help find a way for OMP to help move forward on what Polycephany's goal is, which is to allow script collaboration (in this case Groovy) as I think that Zorrow also is similar (i,e, allow users to share scripts) but I don't believe it's what OMP should promote this to the architect personna under CI/CD and GitHub.
With the mainframe customers I talk to about CI/CD modernization the two tools they used are Zowe and/or Ansible.  CI/CD and GitHut are DevOps tools and Zowe (as well as Ansible) are 2021 DevOps Dozen finalist for Mainframe modernization (as a reference point).  Happy to debate / discuss more.  
- Mainframe Profssional:  Mainframe is also very scalable and highly available, so this should be included in the Architect or Mainframe Professional persona.
- IBM MTM is now called IBM z Explore.
