### ISSUE TITLE
Martino Drot de Gourville

### ISSUE THREAD

**Issue by martinodg** [openmainframeproject/tac#302]
### Email

mdgourville@ctl4.biz

### Bio

[Martin Drot De Gourville - MF Architect.pdf](https://github.com/openmainframeproject/tac/files/7790258/Martin.Drot.De.Gourville.-.MF.Architect.pdf)
[

### Projects within OMP you would want to be an ambassador for

Well, I'm not participating on any official OMP project, but I'm one of the architects involved on a Kyndryl project to build the Ubuntu MicroK8S  platform on zCloud as a commercial offering.  

### List any other topics you would be able to speak about

HybridCloud and Open Source on Mainframe platform

### Why do you want to be an ambassador?

Because I have passion about Mainframe and I was involved on mainframe moderniztion on the last 7 years at least. Mainly on zlinux but not only, 

### Attach a headshot

![20210305_140759](https://user-images.githubusercontent.com/9776865/147696160-b466fc82-fe90-4c5f-a105-6da153a4489c.jpg)

**Comment by jmertic** [comment]
@gmackinnon
