### ISSUE TITLE
Ambassador application - Jose Arias

### ISSUE THREAD

**Issue by JoseAri** [openmainframeproject/tac#306]
### Email

jose.arias@broadcom.com

### Bio

Jose Arias CISSP, ITIL 
EMEA Mainframe Security Technical Consultant @ Broadcom Inc.

Since more than 20 years ago I've been using Debian Linux and other Unix systems such as Freebsd and I have always admired the open source community, having collaborated in projects like GIMP-ES, participating in events like the GUADEC in Seville (GNOME community's largest conference) where I could meet very influential members of the free software community like Miguel de Icaza or Jon "maddog" Hall. 

During the last 12 years I've been always working mainly with Z/Os but I also had the opportunity to work professionally with Unix. Mainly apache, mysql and user administration along with digital certificate management on these systems.

I'm also a professional photographer, but I have stopped this activity for a while since we had a daughter nine months ago. 

### Projects within OMP you would want to be an ambassador for

Zowe

### List any other topics you would be able to speak about

Mainframe Security
Open Source tools
Cyber Security

### Why do you want to be an ambassador?

I want to collaborate again with open source software, taking advantage of the fact that my work allows me a wide relation with it.

### Attach a headshot

![jose2](https://user-images.githubusercontent.com/97041567/147949675-1f080150-1936-4639-b8e7-3a1eb230ec9e.jpg)

**Comment by jmertic** [comment]
@1000TurquoisePogs
