### ISSUE TITLE
Ambassador application - Hartanto Ario Widjaya

### ISSUE THREAD

**Issue by tanto259** [openmainframeproject/tac#309]
### Email

hartanto@securitypuppy.com

### Bio

Hartanto is a computer science student from Singapore Management University. He is currently a committer for the COBOL Programming Course after participating as a mentee during the Open Mainframe Project 2021 Summer Mentorship. He aimed to improve the content of the course with various addition and assists new learners to incorporate COBOL as a part of their tech toolkit.

### Projects within OMP you would want to be an ambassador for

- COBOL Programming Course

### List any other topics you would be able to speak about

- Experience in the OMP Mentorship Program
- Open-source development
- Attracting next generation of talent to the mainframe (with Zowe and DevOps)
- DevOps on mainframe

### Why do you want to be an ambassador?

As a student, I can provide a unique perspective to mainframe-based development and how we can attract newer generation of talent via the use of modern tooling along with connecting them to commonly taught materials on today's era.

### Attach a headshot

https://drive.google.com/file/d/1DYy6FPi0SxXWbR5sBbiZZjtKxX1Z4KXg/view?usp=sharing

**Comment by jmertic** [comment]
Congratulations! You have been accepted as an Open Mainframe Project Ambassador. Look to your email for the next steps.
