### ISSUE TITLE
Ambassador application - Gabor MARKON

### ISSUE THREAD

**Issue by markons** [openmainframeproject/tac#311]
### Email

markons@gmail.com

### Bio

See my LinkedIn site: https://www.linkedin.com/in/gabor-markon-79133220/

### Projects within OMP you would want to be an ambassador for

Mentorship Program - that's what I do already within my organization, but I am open to other directions as well
ZOWE - I suppose I am able to support in areas like Rexx and Java

### List any other topics you would be able to speak about

Mainframe migration - why good, why bad

### Why do you want to be an ambassador?

To support my company and the community to keep the mainframe alive on a long term.

### Attach a headshot

[](url
![Gabor_Markon](https://user-images.githubusercontent.com/2115566/148688394-91d71690-088e-4594-ab74-345aff900601.png)
)

**Comment by KipTwitchell** [comment]
Contact made.  Communication begun.

**Comment by markons** [comment]
Hello Kip,

I am responsible for the Mainframe Academy training in our organization Deutsche Telekom / Hungary branch. 
I'll complete this today, then make a one-week holiday. Then our students make a test, I'll evaluate this in a week, and then I am ready to communicate (3rd March week ca.). Thank you for your understanding!
