### ISSUE TITLE
ADE Annual Review

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#312]
@caffreyj Can you be ready to do the annual review for ADE today at the TAC meeting? Structure of the review defined at https://tac.openmainframeproject.org/process/project_stages.html#tac-review

**Comment by jmertic** [comment]
@caffreyj Can you be ready for the ADE annual review at the 1/20/2022 meeting of the TAC?

**Comment by caffreyj** [comment]
**Current usage**

![FireShot Capture 075 - Traffic · openmainframeproject_ade - github com](https://user-images.githubusercontent.com/17327368/151213883-403bf469-9b11-4f1b-ac50-d64c608d246f.png)

Latest Changes

- fix provided for log4jshell CVE

**Comment by jmertic** [comment]
Thanks @caffreyj - can you be on the call tomorrow to present?

**Comment by caffreyj** [comment]
yes and answer any questions

**Comment by jmertic** [comment]
Great - thank you!

**Comment by jmertic** [comment]
Approved by the TAC on 2/10/2022

https://github.com/openmainframeproject/omp-landscape/pull/446
