### ISSUE TITLE
Sudharsana Srinivasan

### ISSUE THREAD

**Issue by Sudharsana-Srinivasan** [openmainframeproject/tac#324]
### Email

sudharsana.srinivasan@gmail.com

### Bio

Sudharsana Srinivasan is a Program Manager with IBM Z Ecosystem team. She has worked on several IBM Z programs, prominently the COBOL Course that launched on Open Mainframe Project and co-leads the Technical Steering Committee of the project. 

### Projects within OMP you would want to be an ambassador for

COBOL Programming Course 

### List any other topics you would be able to speak about

OMP in general
COBOL in general and OMP COBOL Course
What is Enterprise Computing
Advocating for IBM Z - How To

### Why do you want to be an ambassador?

Since 2020 I have been actively contributing to the COBOL Programming Course and been an advocate and ambassador for the course.

### Attach a headshot

![Sudharsana Srinivasan](https://user-images.githubusercontent.com/62910093/151418939-ac551def-f35d-4f7b-8cff-444651816b10.jpg)

**Comment by jmertic** [comment]
Congratulations! You have been accepted as an Open Mainframe Project Ambassador. Look to your email for the next steps.
