### ISSUE TITLE
Software Discovery Tool annual review

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#353]
For May 10, 2022 meeting

**Comment by jmertic** [comment]
@pleia2 Please share any materials in this issue as a pre-read for the TAC

**Comment by pleia2** [comment]
I have prepared this document which I'll also share on my screen during the meeting: https://docs.google.com/document/d/1k0ghsIKq20TJFGoMdL6kW_IgQgekRycipfh2gQnFIVg/edit?usp=sharing

**Comment by jmertic** [comment]
Renewal approved by TAC on 5/12 - updated landscape.

https://github.com/openmainframeproject/omp-landscape/pull/540
