### ISSUE TITLE
Linux Distributions WG annual review - 11/10

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#359]
@pleia2 Let us know if you are ready for the review /cc @yarille

**Comment by pleia2** [comment]
@jmertic Happy to provide a review soon, but isn't it quite a bit early? We were just approved as a WG on October 14, 2021.

**Comment by jmertic** [comment]
Not a problem - moving it out now

**Comment by pleia2** [comment]
The deck I'll be sharing at the TAC meeting today:

[Linux_Distributions_Working_Group_-_TAC_2022.pdf](https://github.com/openmainframeproject/tac/files/9983173/Linux_Distributions_Working_Group_-_TAC_2022.pdf)

**Comment by yarille** [comment]
Approved for renewal for another year per TAC vote

**Comment by jmertic** [comment]
Updated landscape - https://github.com/openmainframeproject/omp-landscape/commit/d7baeea1e2186d4f5cb8aaf8f5d560eb7110b8a7
