### ISSUE TITLE
Ambassador application - NAME

### ISSUE THREAD

**Issue by ritamgit-alt** [openmainframeproject/tac#365]
### Email

ritamdebnath@icloud.com

### Bio

Hi, I’m Ritam Debnath an IOS Developer who loves to make an impact. I’m a self-taught programmer who is enthusiastic about AI & ML and passionate about Software Development. And also loves to contribute in open-source & loves to create real-world projects and create solutions for complex problems.

### Projects within OMP you would want to be an ambassador for

Software Dicovery Tool

### List any other topics you would be able to speak about

The use of renewable energy increased greatly just after the first big oil crisis in the late seventies. At that time, economic issues were the most important factors, hence interest in such processes decreased when oil prices fell. The current resurgence of interest in the use of renewable energy is driven by the need to reduce the high environmental impact of fossil-based energy systems. Harvesting energy on a large scale is undoubtedly one of the main challenges of our time. Future energy sustainability depends heavily on how the capacity of renewable energy is improved in the next few decades. Although in most power-generating systems, the main source of energy (the fuel) can be manipulated, this is not true for solar and wind energies (Valenzuela, et al, 2004). The main problems with these energy sources are cost and availability, wind and solar power are not always available where and when needed. Unlike conventional sources of electric power, these renewable sources are not “dispatchable”—the power output cannot be controlled. Daily and seasonal effects and limited predictability result in intermittent generation. Some manufacturers has released products to facilitate the integration of renewable energy but the researcher is examining ways of improving the capacity of renewable power system using solar power panel (Camacho et al, 2007). Industry must overcome a number of technical issues to deliver renewable energy in significant quantities.

Control is one of the key enabling technologies for the deployment of renewable energy systems. Solar power requires effective use of advanced control techniques. In addition, reliable electric supply cannot be achieved without extensive use of control technologies at all levels. Solar power plant exhibit changing dynamics, nonlinearities, and uncertainties—challenges that require advanced control strategies to solve effectively. The use of more efficient control strategies would not only increase the performance of these systems, but would increase the number of operational hours of solar and wind plants and thus reduce the cost per kilowatt-hour (KWh) produced. The solar have tremendous potential for fulfilling the world’s energy needs (White House, 2010). One of the greatest scientific and technological opportunities researchers are faced with is approaches to developing efficient ways to collect, convert, store, and utilize solar energy at an affordable cost. The solar power reaching the earth’s surface is about 86,000 TW. Covering 0.22% of our planet with solar collectors with an efficiency of 8% would be enough to satisfy the current global power consumption. Estimates are that an energy project utilizing concentrating solar power (CSP) technology deployed over an area of approximately 160 x 160 km in the Southwest U.S. could produce enough power for the entire U.S. consumption. Solar-sourced electricity can be generated either directly using photovoltaic (PV) cells or indirectly by collecting and concentrating the solar power to produce steam, which is then used to drive a turbine to provide the electric power (CSP).

Concentrating solar thermal systems use optical devices (usually mirrors) and sun-tracking systems to concentrate a large area of sunlight onto a smaller receiving area. The concentrated solar energy is then used as a heat source for a conventional power plant. A wide range of concentrating technologies exists, the main ones being parabolic troughs, solar dishes, linear Fresnel reflectors, and solar power towers. The primary purpose of concentrating solar energy is to produce high temperatures and therefore high thermodynamic efficiencies. Parabolic trough systems are the most commonly used CSP technology. A parabolic trough consists of a linear parabolic mirror that reflects and concentrates the received solar energy onto a tube (receiver) positioned along the focal line. The heat transfer fluid is pumped through the receiver tube and picks up the heat transferred through the receiver tube walls. The parabolic mirror follows the sun by tracking along a single axis. Linear Fresnel reflectors use various thin mirror strips to concentrate sunlight onto tubes containing heat transfer fluid. Higher concentration can be obtained, and the mirrors are cheaper than parabolic mirrors, but a more complex tracking mechanism is needed.

1.2     STATEMENT OF THE PROBLEM

The uncertainty and intermittency of solar generation are major complications that must be addressed before the full potential of this renewable power system can be reached. The researcher provides an overview of a solar power panel with an evolution of electricity networks toward greater reliance on communications, computation, and control which is a way aimed at improving it. The application of advanced digital technologies (i.e., microprocessor-based measurement and control, communications, computing, and information systems) which are expected to greatly improve the reliability, security, interoperability, and efficiency of the electrical grid, while reducing environmental impacts and promoting economic growth will be considered.

1.3     OBJECTIVES OF THE STUDY

The following are the objectives of this study:

1. To provide an overview on renewable power system and its capacity.

2. To examine ways of improving the capacity of renewable power system using the solar power panel.

3. To identify the limitations of solar power system

1.4     RESEARCH QUESTIONS

1. What is renewable power system and its capacity?

2. What are the ways of improving the capacity of renewable power system using the solar power panel?

3. What are the limitations of solar power system?

1.6     SIGNIFICANCE OF THE STUDY

The following are the significance of this study:

1. Findings from this study will educate students on renewable power system with emphasis on solar power system.

2. It will educate researchers on methods of improving the existing solar power technology.

3. This research will also serve as a resource base to other scholars and researchers interested in carrying out further research in this field subsequently, if applied will go to an extent to provide new explanation to the topic.

1.7     SCOPE/LIMITATIONS OF THE STUDY

This study will cover approaches at improving the existing solar power technology with a view of optimizing the operation of the system and minimizing environmental impacts.

LIMITATION OF STUDY

Financial constraint- Insufficient fund tends to impede the efficiency of the researcher in sourcing for the relevant materials, literature or information and in the process of data collection (internet, questionnaire and interview).
Time constraint- The researcher will simultaneously engage in this study with other academic work. This consequently will cut down on the time devoted for the research work.

### Why do you want to be an ambassador?

I have a passion for learning new things, I  enjoy the role. Brand ambassadors learn how to create digital content for social media and become comfortable with different platforms to complete their duties effectively. This position can also help me to learn how to interact with people on social media and keep me updated on new social media trends. A role as a brand ambassador offers many ways to expand your network. Brand ambassadors often have the opportunity to build a wide network of professionals, customers, influential people and executives. A brand ambassador role can be a great addition to my resume because I can showcase my experience and professional skills, which may help increase my confidence as a professional. Showing how I've helped a brand grow may be valuable to potential employers, which might allow me to find job opportunities.

### Attach a headshot

That’s the all why I want to be an Ambassador

**Comment by jmertic** [comment]
Hi, we aren't accepting ambassador applications until later this year. I also don't see any references to the mainframe ecosystem; are you someone heavily involved in that ecosystem now?

**Comment by ritamgit-alt** [comment]
So should I close!
