### ISSUE TITLE
COBOL Working Group Annual Review- 8/25

### ISSUE THREAD

**Issue by yarille** [openmainframeproject/tac#371]
### Please share any additional details on this topic

Reminder for 7/14- @openmainframeproject/cobol-wg-leads. Please let us know if anything has changed and you need to change your date.

### Detail what actions or feedback you would like from the TAC

The current activity of the working group.

Assessment of whether the working group has achieved its goals and/or needs to redefine its charter.

Feedback on its experience as an Open Mainframe Project working group, including benefits from being an Open Mainframe Project working group and areas that the TAC and Open Mainframe Project staff can better support the working group.

**Comment by jmertic** [comment]
Renewed via email - updated on landscape https://github.com/openmainframeproject/omp-landscape/pull/645
