### ISSUE TITLE
New Working Group Proposal - Mainframe Modernization Working Group

### ISSUE THREAD

**Issue by MistyDecker** [openmainframeproject/tac#385]
### Describe the purpose of the group in no more that 4-5 sentences

The term "modernization" is being used to mean different things causing confusion in the market.  Some define "modernization" as moving away from mainframes and COBOL and others define "modernization" as updating existing systems in place.  Modernization, especially application and process modernization, is absolutely essential to the future of the mainframe ecosystem.  The OMP could provide leadership in ensuring that addressing aging applications is done in a way with a broad view of the options, rather than following fashion or tradition.

### Goals of the working group

•	Agree on a common definition of “mainframe modernization”.
•	Create a framework through which all vendors can highlight their modernization options.
•	Produce educational materials about modernization options and actual examples.
•	Create one “go to” place for information about mainframe modernization.
•	Educate the market (mainframe and non-mainframe) via social media, blogs, articles and conferences.
•	Identify opportunities for future OMP projects to enable modernization.

### Non-goals of the working group

•	We will not be developing code or new tooling to aid in modernization as that is already being covered by the various OMP projects.
•	We will not be endorsing any individual vendor products/solutions, keeping the content at the educational level and not marketing.

### Deliverables

Common definition and framework of “Mainframe Modernization”
•	Ensure the market is communicating with a shared understanding of the what modernization means

Educational materials:
•	Research
•	Blogs
•	Presentations

Repository for Mainframe Modernization educational materials
•	Process for reviewing and committing educational materials to ensure not vendor specific

Wish List of Future OMP Modernization Projects
•	What open source tools are needed to aid in the modernization process?

**Comment by jmertic** [comment]
Accepted by TAC.

**Comment by PeterFandelAtRocket** [comment]
Great idea. I'm in.

**Comment by Domenico224** [comment]
I would like to join this working group ... I am one of the product manager working on Zowe.

**Comment by pwmccaffrey** [comment]
Please add me to this working group

**Comment by gmackinnon** [comment]
Please add me to this workgroup too - thanks!

**Comment by rickperret** [comment]
As discussed during the 9/20 Board Mtg in Philly, please add me as the OMP Marketing Committee Rep to this project.   Also,  we need to lead the modernization conversation from a business-first perspective, not technology.    Not saying the TAC doesn't explore architectures and use case, but start from a business POV.

**Comment by jmertic** [comment]
Closing since the group is onboarded now.
