### ISSUE TITLE
Atom Language Syntax Highlighting for z/VM Annual Review

### ISSUE THREAD

**Issue by yarille** [openmainframeproject/tac#387]
### Please share any additional details on this topic

Atom Language Syntax Highlighting for z/VM Annual Review

### Detail what actions or feedback you would like from the TAC

Atom Language Syntax Highlighting for z/VM Annual Review

**Comment by jmertic** [comment]
TAC has approved moving to Emertius per the project's recommendation.

https://github.com/openmainframeproject/omp-landscape/pull/644
