### ISSUE TITLE
Mainframe Project Onboarding Process

### ISSUE THREAD

**Issue by yarille** [openmainframeproject/tac#399]
### Please share any additional details on this topic

-Outline steps to onboard current and new projects

### Detail what actions or feedback you would like from the TAC

-Outline steps to onboard current and new projects

**Comment by jmertic** [comment]
Matt Hogstrom, Lionel Dyck, Sam Golob volunteered to be part of it. John to provide more info to that group and setup discussion call.

**Comment by jmertic** [comment]
Call scheduled for 2/2/2023

**Comment by jmertic** [comment]
If interested - please reach out to @jmertic to indicate if you wish to participate.

**Comment by jmertic** [comment]
Plan in progress at https://docs.google.com/document/d/1d7ZyxvbKwp2P7y_WWbMbdg2LcawFhYkUsxQMdqXE0V4/edit?usp=sharing - please let @jmertic know if you want to join weekly meetings.

**Comment by jmertic** [comment]
Proposal in good shape - will update in next TAC meeting

**Comment by jmertic** [comment]
Folding into #481
