### ISSUE TITLE
Ambassador application - Caitlin Mooney 

### ISSUE THREAD

**Issue by MooKnee** [openmainframeproject/tac#408]
### Email

Mooneycatie@gmail.com

### Bio

Software Engineer @ JPMorgan Chase & Co. || CS @ NJIT '22 || IBM Z Advocate & Student Ambassador || ΔΦΕ Alumnae || Peer Mentor @ NJIT || STEM Tutor & Supplemental Instruction Leader @ BCC || Girl Scout Gold Award Alumnae

I am a recent grad of New Jersey Institute of Technology with a B.S. degree in Computer Science. During my time at NJIT, I was a YWCC Peer Mentor through the Learning Communities program, which allows me to give back to my community, and to be to others the person that I needed when I was starting out in tech. I was very involved on campus, so I also served as the Coordinator of Community Service as a sister of the Delta Phi Epsilon social sorority, Beta Eta chapter. I volunteer regularly and am passionate about privacy, social good, and technology.

My past work experience includes working with clients and colleagues to solve technical infrastructure challenges at UPS, performing STEM & mainframe research and tutoring at BCC, and handling business operations at both Colliers International and Pullman Services.  

My primary career interests are in law and cyber security, and I enjoy learning about privacy, finance, and cryptography.

Outside of growing my career, I enjoy nerding out, staying active, and playing with my bird.

### Projects within OMP you would want to be an ambassador for

Education, mentorship

### List any other topics you would be able to speak about

COBOL (potentially?)

### Why do you want to be an ambassador?

Mainframe systems are my passion, and I have received so much back from this amazing community that I want to give back in any way that I can.

### Attach a headshot

![Screenshot_20220414-010524_Drive_19048743870857](https://user-images.githubusercontent.com/42590833/202792256-4eab4cc9-e450-4147-a125-e45c2d4e3151.jpg)

**Comment by yarille** [comment]
Application accepted by the TAC
