### ISSUE TITLE
Ambassador application - Goitsemang Lebane

### ISSUE THREAD

**Issue by GoitsemangLebane** [openmainframeproject/tac#409]
### Email

lebaneaustin2@gmail.com

### Bio

`I believe that with our help computers can change your very tough task into an easy one.`

### Projects within OMP you would want to be an ambassador for

ZOWE

### List any other topics you would be able to speak about

Building dockerHub development stacks

### Why do you want to be an ambassador?

I am into tech and has developed a lot of tech projects such as deep learning classifier, deep learning & NLP AI chatbot, Steganography Software and a blogging website `https://techigonic.liveblog365.com` where I write all about tech and give people some advices on what to do.

I want to help others transition well into technology and for them to understand that technology is the future, they need to know how to use and operate it

### Attach a headshot

Refuses to attach a headshot

**Comment by yarille** [comment]
Application NOT approve by the TAC
