### ISSUE TITLE
Marcus Davage

### ISSUE THREAD

**Issue by spufidoo** [openmainframeproject/tac#410]
### Email

marcus_davage@bmc.com

### Bio

Having graduated in Computer Science at Aberystwyth in 1990, Marcus has worked with mainframes ever since, as a programmer, systems programmer, consultant, database administrator, production support hero, production support villain and management piñata for various companies. He is now lead product developer for BMC Software. He holds an MBCS, CEng, CITP, and more often than not, a glass of wine. He is an IBM Champion, joint chairman of the UK Db2 User Group, a member of the IDUG Content Committee and the GSE Conference Planning Committee. In his spare time, he is a STEM Ambassador, leading Code Clubs in Welsh-speaking junior schools, and thrilling the next generation at the prospect of technology as a career. He blogs and casts pods, too.

### Projects within OMP you would want to be an ambassador for

Zowe
Education
CBT-Tape

### List any other topics you would be able to speak about

Db2, SQL, performance, design, development.
Python, REST Services, DevOps, Mainframe Modernisation.

### Why do you want to be an ambassador?

I already am a STEM Ambassador and an IBM Champion. I work for BMC Software, which is a project member. I am a software developer that loves using Visual Studio Code, Zowe, and their Db2 Extensions.

### Attach a headshot

![Mini Me](https://user-images.githubusercontent.com/9607924/203574981-b6c0e79b-46d1-47d9-a0a7-70129d4a4935.jpg)

**Comment by yarille** [comment]
Application accepted by the TAC
