### ISSUE TITLE
Misty Decker

### ISSUE THREAD

**Issue by MistyDecker** [openmainframeproject/tac#424]
### Email

mistyvdecker@gmail.com

### Bio

Misty’s 30-year career can be described in two words:  mainframes and people.  A frequent speaker and advocate for mainframe and COBOL modernization, Misty is Director of Product Marketing at Micro Focus and serves on the Open Mainframe Project’s Governing Board and chairs the Modernization Working Group of the Linux Foundation. She helps organizations understand the full range of options for leveraging their existing IT assets and core applications in new ways to better meet the modern needs of the organization.  Active in Diversity and Inclusion, she’s a frequent speaker on Unconscious Bias and mentors a wide range of people starting their IT careers.

### Projects within OMP you would want to be an ambassador for

Modernization Working Group
COBOL Working Group

### List any other topics you would be able to speak about

All of it!  jk
My most frequent topics are:

- Mainframe Modernization
- COBOL
- Skills
- What are mainframes
- Unconscious bias in technology
- Mainframe and cloud

### Why do you want to be an ambassador?

I'm quite passionate about mainframes, COBOL, skills and I think the Open Mainframe Project is the best way to reach a broader audience, creating a more inclusive engagement with the broader tech community.  Plus, I just really love taking every opportunity to talk to people and share my passion.

### Attach a headshot

![Misty_Decker_20220117_IMG_2673](https://user-images.githubusercontent.com/80010168/210443098-2fbf4742-002c-4ab4-b5f1-163aed5c00da.jpg)

**Comment by yarille** [comment]
Application not chosen by the TAC
