### ISSUE TITLE
Ambassador application - SUBHRANEEL HALDAR

### ISSUE THREAD

**Issue by Subhraneel77** [openmainframeproject/tac#426]
### Email

subhraneel777@gmail.com

### Bio

Hi, I am Subhraneel Haldar. I am currently pursuing my undergrad in Computer science and engineering from BPPIMT, West Bengal. I am presently in my 3rd year. I am enthusiastic, dynamic as well as a quick learner. I love to learn new things and when it comes to technology my interest point of view increases to a broader respect. I love to teach students and also loves to aware students about the latest technologies and research points. I am an active member of various committees on my campus having successfully organised a couple of events on my first year itself. Talking about my technological inclinations , I am presently a Google Cloud Computing Enthusiast. I preferred doing several projects in this field . I am currently working on a very interesting research  project of writing anything just by thinking without any interference of hands touch. This project will be build using AI and will be beneficial for millions of people.
I am a Open Source Contributor at Gsoc. I have been  a part of Google Cloud Facilitator Program. I have seen that students in my college has great ideas but they cannot have real life implementation as they cannot grab an opportunity due to lack of resources and proper guidance. I want to be a helping man to all those students who also loves to learn like me . So, I want to gain experience as well as learn about such vast ML,AI ,Cloud etc technologies. Communicate with lots all other tech enthusiasts and learn from them, grow with them. I am currently NSCC club lead in my campus as well as lead member of GDSC . I am the founder of Extendo Community. Overall, all this engagement and connections will help me to strengthen my Community with knowledge and Professional members.

### Projects within OMP you would want to be an ambassador for

Guiding Students 
Education
Mentorship

### List any other topics you would be able to speak about

Git & Github
Google Cloud Fundamentals
Communication Skills 
Various Technologies 
How to Lead A Community 
Teach any C,C++,Python etc languages

### Why do you want to be an ambassador?

At the very first instance, joining a student organisation presents many opportunities to learn more about yourself, our goals, and our strengths. We can learn from how other students handle certain situations and test our current knowledge. We can also find out what we’re good at, whether that’s multitasking, staying organised, generating ideas, or serving others. This self-awareness will be beneficial in your future career. Developing the fluency with soft skills allow us to effectively interact with others, like communication, attitude, and work ethic. Joining a Community not only teaches us these skills, but also helps us broaden and improve those we already have. Knowing how to work well with a team is an essential skill for any career. Being in a student organisation teaches us how to do this by putting us in situations where we are required to take advice from others, as well as give our own. We will also get networking opportunities. Meeting new students, making connections, and building relationships will all help down the line when we’re looking for a job. We’ll learn how to engage with diverse groups of people and this diversity in people play a major role in our life. Becoming a leader in this organisation will help us develop leadership skills that will be invaluable in all areas of life. We’ll be presented with opportunities to improve in public speaking, and gain confidence in yourself as an individual. This organisation will also provide opportunities to give back to the community, whether through acts of service, sponsoring events, or hosting some useful events for students. And lastly the most important criteria in any work is to have Fun in doing so. Meeting new people, making new friends, and participating in activities will help us make the most of your graduate college experience. As I have been a part of Huge Open Source Project Community Of CircuitVerse. I Know how it really feels enthusiastic self -motivating to be a part of a Community. Team leaders are central factors in a company's success and are crucial to motivating employees and maintaining high morale. Through clear communication, they help set goals and guide teams toward overall success. Being a team leader for me has been exciting and challenging. To manage a team you have to understand human psychology because no two humans are exactly the same, so as a leader you have to understand how to deal with everyone uniquely. In my case, I have had to develop some personal relationship to connect with my team emotionally and that has helped in critically balancing the overall mindset and productivity of my team as regards to the organisation’s goals and vision. Smiling and cheering my team up always as a leader in a bad mood is a major cause discouragement to the whole team. The most challenging scenario I had faced in my life when my personal instincts are somewhat against my team opinions regarding a solution graph but I took a grave brave decision of going with my opinion and lastly making it correct was really a great achievement in my career as a leader. Being Cool , Organised , Seniority of service, Problem solving capability , Ability of taking grave decisions etc I believe made me a good team leader. A successful leader is also a good communicator. I’m dynamic; I'll change my leadership style as circumstances necessitate it. I'm concerned with efficiency, deadlines, goals, and long-term vision, but I also know my team is comprised of humans and sometimes things happen which gets complicated but as I'm super organised, don't mind delegating tasks, and would confront conflict instead of avoiding it. And the best part of being a leader is the respect you earn from your team members which I believe play major inspiring role in someone’s life. On an individual level I tried to mentor a handful of students to organise events and make them aware about the new technologies. Providing them with resources and opportunities available on the internet and also motivating as well as helping them to contribute to open source. 

### Attach a headshot

![Fb RadheKrishna](https://user-images.githubusercontent.com/75981967/210958414-cb90bf90-4663-4899-b626-3011118e2e46.jpg)

**Comment by yarille** [comment]
Application NOT accepted by the TAC
