### ISSUE TITLE
Ambassador application - Jakub Balhar

### ISSUE THREAD

**Issue by balhar-jakub** [openmainframeproject/tac#427]
### Email

jakub@balhar.net

### Bio

I am a long-term enthusiast interested in building secure products and solutions serving customers. Currently, I am working with Broadcom as Product Owner for the API Mediation Layer, and I am Zowe TSC Chair and Zowe API ML Squad Lead. I am also involved in the propagation and presentation of Zowe on the conferences around the world. 

Before joining Broadcom, I worked as the Head Of Application Development in a small Czech company named Gisat. Most of the project's we were involved with were for NASA and ESA. I was also presenting often on conferences in the space industry. 

Meanwhile, I published a book focusing on Web Accessibility for people with Dyslexia, including the tools to evaluate whether the webpage is effective for people with dyslexia. 

As a side project, I have been running a https://larpovadatabaze.cz/ collection of all the larps that were run in the Czech Republic, including the ratings and comments. 

### Projects within OMP you would want to be an ambassador for

Zowe, as the Technical Steering Committee Chair, I would like to be more involved in the PR for the project and the Open Mainframe Project in general. 

### List any other topics you would be able to speak about

Mainframe Modernization, Hybrid Cloud, Dev Sec Ops, Open Source and Security, Mentoring within te Open Source

### Why do you want to be an ambassador?

Because after two years of leading the Zowe and one of its squads, I have a unique insight into what it take to run an Open Mainframe Project's project. What good Zowe and OMP brings to the world of the mainframes and given my previous role as Head of Software Engineering in the Distributed World I also understand the difference and value as opposed to the distributed community and in the integration with the same tools.  

### Attach a headshot

![1610464552862](https://user-images.githubusercontent.com/1757251/211047383-3671f321-c86f-433c-af67-b0404ea7a1cb.jpeg)

**Comment by yarille** [comment]
Application accepted by the TAC
