### ISSUE TITLE
Ambassador application - Dan Kelosky

### ISSUE THREAD

**Issue by dkelosky** [openmainframeproject/tac#428]
### Email

dkelosky@gmail.com

### Bio

Dan Kelosky is a Software Architect helping to build Devops and Zowe solutions within Broadcom.  Dan started mainframe development in 2009 coding IBM assembler and Metal C.  He has since written code for web UIs (HTML, CSS, & Typescript), for distributed systems (C++, Java, & Node.js), and for desktop applications (Node.js, Rust).

### Projects within OMP you would want to be an ambassador for

Zowe

### List any other topics you would be able to speak about

Mainframe software development, Node.js, TypeScript, HLASM, Metal C, VS Code Extension Development

### Why do you want to be an ambassador?

I try to be one already through [medium posts](https://medium.com/@dkelosky), [LinkedIn](https://www.linkedin.com/in/dkelosky/), [SHARE participation](https://www.share.org/blog/use-zowe-to-broaden-assembler-development-practices), and [coding within Zowe](https://github.com/zowe/zowe-cli/commits?author=dkelosky).

### Attach a headshot

![image](https://user-images.githubusercontent.com/14940561/211051346-ca6fb268-8351-4aeb-8c2e-53d01dbd8a60.png)

**Comment by jmertic** [comment]
Hey @dkelosky - since you are already an Ambassador - no need to reapply.
