### ISSUE TITLE
Matt Hogstrom

### ISSUE THREAD

**Issue by hogstrom** [openmainframeproject/tac#429]
### Email

matt@hogstrom.com

### Bio

Matt has been involved with the mainframe since the days of the dinosaurs.  He started as a batch assembler, moved onto systems programming and worked as a consumer of IBM z/OS, VSE and z/VM services for over 20 years.  In addition, Matt has been actively involved to integrate distributed technologies with the mainframe starting with Novell Networking allowing CICS to print to distributed printers not registered with the mainframe.

In early 2000 Matt switched to the darkside of creating IT products when he joined IBM.  He was involved in the formation of Java at IBM participating in the Java Community Process (JSR-004 and JSR-131) as well as building performance benchmarks at SPEC (SPECjAppServer 2001 and SPECjAppServer 2004).  He is also a member of the Apache Software Foundation and participated on Apache Geronimo which was used to create the WebSphere Community Edition.  In all these efforts they were focused on the union of the Mainframe and Distributed usage. 

Later he took on the role of CTO of the IBM z Manage suite of products and was a founding member of the Zowe Community which is the most active OMP project having broad reach to join mainframers to open source technologies.

Currently Matt is a Distinguished Engineer in AIOPs at Broadcom.  Matt’s role at Broadcom is to explore ways to simplify using Broadcom Monitoring and Automation products by enabling them to be easily consumable as RESTful services to create better solutions and outcomes for our products and customers.

### Projects within OMP you would want to be an ambassador for

Zowe
Mainframe Modernization

### List any other topics you would be able to speak about

Career advice for those considering being a mainframer which includes the industry, culture along with the technology.

How to help people find a path to engage with open source.

The benefits of Linux and K8s for the IBM Z platform across z/OS and other operating systems.

### Why do you want to be an ambassador?

I really enjoy sharing my experience with others with the goal of providing knowledge transfer and inspiration.  If we only do but do not share and pass the torch our impact is limited.  My intention is to share, inspire and encourage others to see evolving IT and role of the mainframe in that ecosystem.  

### Attach a headshot

![me_cartoonFilter-1136x640](https://user-images.githubusercontent.com/2906023/211055005-895ee87f-3b6f-47c4-9ac5-1eaa1d97b504.jpg)

**Comment by jmertic** [comment]
Hey Matt - since you are already an Ambassador - no need to re-apply.
