### ISSUE TITLE
Ambassador application - Michael Bauer

### ISSUE THREAD

**Issue by MikeBauerCA** [openmainframeproject/tac#431]
### Email

Michael.Bauer2@broadcom.com

### Bio

Michael is a Product Manager at Broadcom with a focus on DevOps solutions. With a wealth of experience in Zowe technology, including serving as a former squad lead and TSC member, Michael is a go-to expert in the field. In addition to his work with Zowe, he is also currently a TSC member for the COBOL Programming Course.

### Projects within OMP you would want to be an ambassador for

Zowe, COBOL Programming Course

### List any other topics you would be able to speak about

DevOps, Software Supply Chain Security, Mainframe Modernization

### Why do you want to be an ambassador?

I have certainly enjoyed the opportunity to work on these open source projects and would like to share the value they add with others. As a current ambassador, I have consistently promoted these projects via mentorship, community events, [blogs](https://medium.com/@michael.bauer2), and webinars/demonstrations.

### Attach a headshot

![Profile_Pic](https://user-images.githubusercontent.com/35504792/211096098-08f37740-f527-4de0-892e-eceb5a4a29be.jpg)

**Comment by yarille** [comment]
Already an ambassador, no need to reapply.
