### ISSUE TITLE
Joe Bostian

### ISSUE THREAD

**Issue by jbostian** [openmainframeproject/tac#432]
### Email

jbostian@us.ibm.com

### Bio

I have developed and tested server side code throughout my career with a focus on the higher levels of the stack - from middleware to application runtime environments.  As Linux has matured over the years, and the open source model has become the dominant workflow for dev/test, I have centered my efforts on open source issues in the mainframe environment - from z/OS to Linux on Z.  Most often these efforts are in support of AI and machine learning workloads.  I work with several groups within and around the Open Manframe Project, and see this community as a key means to ensure a long and vital future for our platform and those who use it.

### Projects within OMP you would want to be an ambassador for

Ambitus, and Software Discovery Tool

### List any other topics you would be able to speak about

- Open source software security
- Mainframe opportunities and challenges with open source software

### Why do you want to be an ambassador?

Open Source Software (OSS) security is a pervasive issue that affects the entire software industry.   The mainframe community has a particularly relevant perspective, because we take security more seriously than any other platform.  This gives us an opportunity to be a part of the industry-wide discussion in a way that hasn't been available to us before.  While several groups focus on different important facets of the security issue, the breadth of our concerns from the bottom of the software stack to the top means that we can strengthen our position as software experts, and not just platform experts.  I want to evangelize this message through the OMP so that we can be seen as true full stack experts when it comes to issues of OSS security. 

### Attach a headshot

![JABostian_2017-profile-400](https://user-images.githubusercontent.com/18175421/211345450-3d785c5f-7981-4513-8288-68687878472b.jpg)

**Comment by yarille** [comment]
Already an ambassador, no need to reapply.
