### ISSUE TITLE
Ambassador application - Rune Christensen

### ISSUE THREAD

**Issue by Rune-Christensen** [openmainframeproject/tac#433]
### Email

ruc@bankdata.dk

### Bio

I am a Lead Software Developer working at Bankdata Denmark. With a Master in Software Engineering as background. He started working with the mainframe in 2006. 
I am a member of the Mainframe Developer Tools team in Bankdata; the team is responsible for providing tools, support and education for all mainframe developers in Bankdata. 
Current focus of the team is to lift Bankdatas mainframe development to a DevOps mindset. 
Besides team projects, I work with COBOL and SQL performance, pushing shift left to the developers, and trying to convince management that it is a good idea. 
I am a member of the Technical Steering Committee for COBOL-Check, and is the current administrator of COBOL-Check.
I have also presented at GSE-Nordic several times, including a presentation about COBOL-Check. Together with Joe Winchester I have presented Bankdatas move towards DevOps and a modern toolstack at IBM Open Z days, and at the latest IBM Open Z day I presented COBOL Check. I was interviewed for the Open Mainframe project where I presented Bankdatas journey, the video was released by the Open Mainframe project in December.

### Projects within OMP you would want to be an ambassador for

COBOL-Check

### List any other topics you would be able to speak about

Performance tuning in SQL and COBOL 
Implementing performance optimal compiler options in COBOL
COBOL-Check 
Moving an organisation towards Clean Code, DevOps and Left-shifting, including moving to modern IDEs, Git controlled source code, Jenkins pipelines and Artifactory for COBOL developers.
Using Zowe in modern IDEs and pipelines.

### Why do you want to be an ambassador?

At Bankdata we intend to keep managing, fixing bugs, and promoting COBOL-Check. 
I am Bankdatas primary spokesperson for COBOL-Check, be it through conferences or interviews. 
I will continue to be available for sparring, interviews and conferences, and Bankdata will continue to promote the usage of COBOL-Check.
I believe that early testing is a very undervalued skill and should be promoted a lot more than it currently is. Especially amongst software developers working with languages where an early testing tool is or was not existing. 
I have a passion for promoting early testing, be it unit, component or integration tests, and I try to enable pull where possible, and push it where I can.

### Attach a headshot

![bduruc_LThumb](https://user-images.githubusercontent.com/26797797/211495183-f13b12de-8ab6-472a-b1aa-13b9bb016c91.jpg)
![Profil billede](https://user-images.githubusercontent.com/26797797/211496226-525ebeed-27c6-4854-8278-0ecedeccb585.jpg)

**Comment by yarille** [comment]
Application accepted by the TAC
