### ISSUE TITLE
Ambassador application - Domenico D'Alterio

### ISSUE THREAD

**Issue by Domenico-DAlterio** [openmainframeproject/tac#434]
### Email

Domenico.DAlterio@it.ibm.com

### Bio

Domenico D’Alterio is the IBM Principal Product Manager focused on The Linux Foundation's ZoweTM and IBM Z distribution for Zowe projects. He contributes to the open-source project strategy and direction as well as market success of IBM Z distribution for Zowe.
Prior to his current role, Domenico was the Product Manager for offerings in the IBM Z AIOps area working on the strategic directions of multiple offerings. In the previous years, he covered different managerial positions in IBM Development and Customer support organization as well as the role of Product Manager of Z Analytics products, Domenico joined IBM in 1999. Starting as designer, moved to a managerial role in 2006, acting as Development and Customer Support manager in the former Tivoli division of IBM. He graduated in Electronic Engineering, in Italy.

### Projects within OMP you would want to be an ambassador for

Zowe

### List any other topics you would be able to speak about

Extensions of Zowe in the System Management area.

### Why do you want to be an ambassador?

I joined Zowe project at the beginning of 2022 and I think that there is agreat potential in this project.
Benefit for the users that are already leveraging the framework are incredible and I would like to help in spreading the word about the project, use cases to attract more users and contributors.

### Attach a headshot

![Domenico D'Alterio](https://user-images.githubusercontent.com/82607792/211798676-dbfa64b5-7d11-4823-a8a6-16ea2c83ba7a.jpeg)

**Comment by yarille** [comment]
Application accepted by the TAC
