### ISSUE TITLE
Ambassador application - Boris Petkov

### ISSUE THREAD

**Issue by boris-bc** [openmainframeproject/tac#437]
### Email

boris.petkov@broadcom.com

### Bio

Engineering manager for the Zowe API Mediation Layer teams at Broadcom Software.

### Projects within OMP you would want to be an ambassador for

Zowe

### List any other topics you would be able to speak about

DevOps
High-performing Teams

### Why do you want to be an ambassador?

I am already engaged in preparing and providing Zowe workshops on behalf of Broadcom. Last year I delivered a one-day workshop to a group of students at the University of Ghent, Belgium. My daily job is to manage the Zowe API Mediation Layer and our current focus is adoption. Becoming an ambassador would be an attempt to further promote Zowe to mainframers but also bring back feedback and remain connected with the community. The success of Zowe is my personal success as well.

### Attach a headshot

![1 (3)](https://user-images.githubusercontent.com/63061368/212014006-57cecdf1-7862-49b3-8f17-476ee1f66eba.JPG)

**Comment by yarille** [comment]
Application accepted by the TAC
