### ISSUE TITLE
Abdullah Kazi

### ISSUE THREAD

**Issue by AbdullahKazi500** [openmainframeproject/tac#438]
### Email

kazi.abdullah.temea66@gmail.com

### Bio

Abdullah is a technology enthusiast
His interest lies in theoretical and computational research especially in physics and Thermodynamics 
His strength lies in dedication and passion to his work which is reflected in his experience 
With a tech savvy mindset, he has the ability to be an asset to any organization
He has proven his mettle by showcasing his capability in various tasks and different situations 
and in his leadership skills 
He has been involved in different non-technical roles previously
which includes supply chain management 
Abdullah was selected as an IBM Z Ambassador to facilitate mainframe education
Abdullah has also worked in open-source quantum computation
Apart from that he is interested in theoretical physics and quantum mechanics along with high energy physics 
His research is focused on particle physics
multi physics, High energy physics & Thermodynamics
Abdullah is open for collaborative research on different projects and research opportunities

### Projects within OMP you would want to be an ambassador for

[Anomaly Detection Engine for Linux Logs (ADE)](https://www.openmainframeproject.org/all-projects/anomaly-detection-engine-for-linux-logs-ade)
[Mentorship Program](https://www.openmainframeproject.org/all-projects/mentorship-program)
[Ambitus](https://www.openmainframeproject.org/all-projects/ambitus)

### List any other topics you would be able to speak about

Quantum computing
Mainframe enterprise systems

### Why do you want to be an ambassador?

As an efficient Orator with a Business Acumen I have the skills and the attitude needed for this role and it's reflected in my work experience I have attended and hosted many Seminars and have organized many intercultural events in my Institute My experience with various Industries and sector is Vast as I was a working with a Ecommerce Transaction company for which I was a lead in the marketing campaign for a App in which my core responsibilities were brand promotions and outreach .I have also worked for a Non-Profit Organization during which my work was to deploy various marketing strategies related to Edtech ventures .I was solely responsible to conduct workshops for 50+student in IIT Madras research park in Artificial intelligence. As a Campus Ambassador for Dockship Dockship is a platform hosting various hiring Hackathons and challenges for AI My responsibilities were to conduct various workshops and brand promotions for various process .During my externship at AT&T Mobility I learned about various business models and How technology is used to create e-commerce business growth After which I was selected as an IBM Z ambassador a flagship event for IBM wherein I was responsible for Facilitating IBM Z Education was also an advocate for CRIO DO CRIO Is a platform for educating students about web development and hiring challenges as. an advocate my job was to teach. And facilitate the students with different technologies. I was also responsible for brand growth and marketing 
Being an ambassador is a deeply rewarding opportunity both on a personal level and also in terms of your career prospects.
This Program will give me an opportunity to Develop my skills.
As an Ambassador I Will have the opportunity to get involved with many different types of work allowing me to develop skills in mainframe enterprise computing 
As an aspiring Ambassadors I am typically confident, dynamic. 
Some of my interpersonal skills
Public Speaking
Communication and interpersonal skills
Presentation skills
Teamwork
Networking
Influence
As an ambassador and as part of this role, I will relay information about the open mainframe project experience to the prospective students of tomorrow. 

### Attach a headshot

![nbnn](https://user-images.githubusercontent.com/75779966/212081616-9caba15d-19e6-4e7c-907d-55abf0e6df5d.PNG)

**Comment by yarille** [comment]
Application NOT accepted by the TAC
