### ISSUE TITLE
Ambassador application - Dong Ma

### ISSUE THREAD

**Issue by larainema** [openmainframeproject/tac#440]
### Email

winterma.dong@gmail.com

### Bio

Dong Ma has worked at IBM China as Software Engineer since 2019. He's been an active technical contributor to OpenStack since the Liberty release, focusing on Infrastructure, Jenkins, OpenStackCI and QA. He now works at IBM LinuxOne Dev Team focusing on Infrastructure, CI/CD automation. He has previously been a speaker at OpenStack Summit, LCA2017, LinuxCon Japan, FOSSCON and the other open source conference.

### Projects within OMP you would want to be an ambassador for

I have contribute to Feilong project, so I would want to be an ambassador for Feilong project.
I am also interested in Zowe project.

### List any other topics you would be able to speak about

DevOps, CI/CD, Infrastructure as s Service, OpenStack, Hybrid Cloud 

### Why do you want to be an ambassador?

- Interested in Open Source, and would like to contribute more to Open Source Project.
- Would like to promote open source on mainframe in China and APAC
- Willing to speak at community events

### Attach a headshot

![Ma Dong](https://user-images.githubusercontent.com/5294029/212625212-2b20997b-0ebd-40e9-bf1c-4d5894d02719.jpg)

**Comment by yarille** [comment]
Application accepted by the TAC
