### ISSUE TITLE
Ambassador application - Fernando Rijo Cedeno

### ISSUE THREAD

**Issue by zFernand0** [openmainframeproject/tac#441]
### Email

fernando.rijocedeno@broadcom.com

### Bio

Fernando is a Software Engineer at Broadcom and an active committer to the Zowe Explorer (VS Code), the Zowe Command Line Interface (CLI), and the Zowe SDKs. He has worked on projects varying from low-level z/OS tools, to middleware, to high level web and mobile applications. With these projects, he has worked on many programming languages and frameworks, including (but not limited to) REXX/OML, TS, Node.js, Flutter, Angular, Ionic, CSS/SCSS, HTML, C/C++, Python, Groovy, Java, Kotlin, and others.

### Projects within OMP you would want to be an ambassador for

Zowe

### List any other topics you would be able to speak about

- Zowe CLI (and plug-ins)
- Zowe Explorer (VS Code Extension)
- Zowe SDK (for Node.js and Python)
- Node.js
- Typescript
- GitHub Actions

### Why do you want to be an ambassador?

I would like to continue my journey in educating and contributing to Open Source Software, and being an Ambassador might help me do just that. As a contributor to multiple Zowe projects, I am daily committed to make the mainframe platform better than the day before.

### Attach a headshot

![Fernando-profile-photo-4k-square](https://user-images.githubusercontent.com/37381190/212933266-9204a0bb-1e96-4b07-bf03-2ec4e8713ffc.png)

**Comment by yarille** [comment]
Application accepted by the TAC
