### ISSUE TITLE
Ambassador application - samuel dion

### ISSUE THREAD

**Issue by sam94dion** [openmainframeproject/tac#442]
### Email

Sam94dion@gmail.com

### Bio

6 years within the mainframe modernization trend. Currently working at desjardins bank in Canada on the mainframe. Tech lead with the mission to modernize the mainframe for the 200 devs within the company. I know Peter and Dan that are in that are in the project. 

### Projects within OMP you would want to be an ambassador for

Cobol-check and other that may need support.

### List any other topics you would be able to speak about

Cobol, devops within the mainframe.

### Why do you want to be an ambassador?

To be part of the community and be part of the lastest technologies.

### Attach a headshot

![Uploading Screenshot_20230111-201700_Gallery.jpg…]()

**Comment by yarille** [comment]
Application NOT accepted by the TAC
