### ISSUE TITLE
Simon Paul

### ISSUE THREAD

**Issue by simonpaulb** [openmainframeproject/tac#443]
### Email

simonpaul0720@gmail.com

### Bio

I'm an COBOL analyst programmer with an experience of 8.8 years. Looking forward to learn new things and showcase my expertise to the best of the community.

### Projects within OMP you would want to be an ambassador for

COBOL related project's.

### List any other topics you would be able to speak about

Cloud and COBOL integration.

### Why do you want to be an ambassador?

COBOL is an age old language, but itd legacy code is still dominating the business. So, always wanted to learn more and explore new things.

### Attach a headshot

Simon

**Comment by yarille** [comment]
Application NOT accepted by the TAC
