### ISSUE TITLE
Annual Review 7/13 - ADE

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#448]
### Please share any additional details on this topic

Annual Review for the ADE project

### Detail what actions or feedback you would like from the TAC

@caffreyj - let's schedule this for the meeting on 2/9 if that works for you.

**Comment by jmertic** [comment]
@caffreyj - when can we reschedule?

**Comment by yarille** [comment]
Rescheduled for 4/24

**Comment by yarille** [comment]
@caffreyj I moved this to June 8 at your request for a May or June date. Please let me know if there are any conflicts.

**Comment by yarille** [comment]
Moved to 7/13 per request from @caffreyj.

**Comment by jmertic** [comment]
Moved to Emertius per TAC vote.

https://github.com/openmainframeproject/omp-landscape/pull/765
