### ISSUE TITLE
Annual Review - COBOL Check - 6/8

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#449]
### Please share any additional details on this topic

Annual Review for COBOL Check

### Detail what actions or feedback you would like from the TAC

@neopragma How about we schedule this for the 2/9 meeting of the TAC if that works for you?

**Comment by jmertic** [comment]
@neopragma - When can we reschedule?

**Comment by jmertic** [comment]
@yarille This is incorrect - z/OS Open Enablement was moved to Emertius. Reopening.

@neopragma I believe you were originally scheduled to do the annual review today - could we move it 6/8?

**Comment by jmertic** [comment]
@neopragma are you able to present for the annual review on Thursday?

**Comment by yarille** [comment]
Project renewed at incubation for another year by TAC vote. 6/21/2023
