### ISSUE TITLE
Annual Review - Open z/OS Enablement Working Group

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#450]
### Please share any additional details on this topic

Annual Review - Open z/OS Enablement Working Group

### Detail what actions or feedback you would like from the TAC

@KipTwitchell - could we schedule this for the 2/23 TAC meeting?

**Comment by KipTwitchell** [comment]
@jmertic David Edelsohn and I just discussed it on our monthly call just now; I'm available to review it on the 23rd.  I think we're going to ask if there is a usefulness for the group in some future way, or perhaps the efforts should be pursued in some other way.

**Comment by jmertic** [comment]
Makes sense - thanks! @yarille please make sure they are set on the agenda.

**Comment by yarille** [comment]
Project approved to move to Emeritus
