### ISSUE TITLE
Annual Review - Zorow

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#451]
### Please share any additional details on this topic

Annual Review - Zorow

### Detail what actions or feedback you would like from the TAC

@shreeji818 Could we schedule this for the TAC meeting on 2/26?

**Comment by shreeji818** [comment]
Yes. We can schedule Zorow review for 2/26 meeting.

**Comment by jmertic** [comment]
Excellent - thanks!

**Comment by yarille** [comment]
Project approved to move to emeritus status by TAC
