### ISSUE TITLE
tersedecompress - move it out of Emeritus status

### ISSUE THREAD

**Issue by alexgubanow** [openmainframeproject/tac#468]
### Please share any additional details on this topic

I would like to take maintainership of tersedecompress app

### Detail what actions or feedback you would like from the TAC

Can we change the status to Active ?

**Comment by jmertic** [comment]
cc @gfrix

**Comment by yarille** [comment]
This was not discussed on 3/9. I will keep it on the agenda for 3/23. @alexgubanow, can you join the meeting?

**Comment by alexgubanow** [comment]
Hi, sorry, I got sick, the rotavirus. It keeps me a bit busy at the moment.
I should be back on track till 3/23, thank you.

**Comment by yarille** [comment]
No worries. I hope you get well soon!

**Comment by alexgubanow** [comment]
Hi @yarille , the meeting link going to be same as for "2nd Thursday of the month" ?

**Comment by jmertic** [comment]
Updated landscape: https://github.com/openmainframeproject/omp-landscape/commit/499cb92cedcc742ef51db06cb5c7caea70cc346c

Updated artwork repo: https://github.com/openmainframeproject/artwork/commit/4acb03a01624fe5598b2fcf6b4fb8dddcf763b2b
