### ISSUE TITLE
Swag Proposal for Open Mainframe Project Slack to Reduce Channel Pollution

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#484]
From @lbdyck:

# Overview
Open Mainframe Project maintains a Slack workspace (Slackspace) for use by Open Mainframe Project and by the approved, and sponsored, projects. Within the Slackspace are channels for use by everyone such as the general channel, and channels for specific projects such as the Cobol-programming-course. 
When one channel is used by those who should be using another channel the result is channel pollution. In many cases this occurs due to ignorance on the part of the user as a result of the user not being aware of the proper use of the various channels.
# Proposal
To reduce Slack channel pollution, I’m proposing the following steps to occur:
## Project Onboarding Webpage
On the Open Mainframe Project site there should be a page with a list of projects and under each project should be pages with more information on the project. One of those pages should be Slack usage guidelines.
The guidelines may include:
1.	Post all questions, issues, etc. regarding the project in the projects Slacks channel.
2.	Keep sensitive information out of the channel – if that is needed then use a direct message
3.	Slack instructions on how to use DMs
4.	Do not use the General channel for project related posts
## Update the Individual Project Slack Channels with a Bookmark
Slack supports creating a bookmark that is available at the top of each channel, and is unique to that channel. A bookmark referencing the usage guidelines should be placed on each channel that points to the usage guidelines for that project.

**ACTION: Please use this thread as a way to discuss and refine the approach. Thank you!**

**Comment by lbdyck** [comment]
One thing each channel owner needs to be aware of is the use of pinned discussions. The pin works while the discussion is active but it appears that the OMP Slackspace is on the free level which means that all discussions go away after 90 days and at that time the pin should go away - I haven't tested this.

**Comment by lbdyck** [comment]
I found that some  pinned items from over a year ago are visible when you click the pinned button - you can view the pinned item in the pinned list but if you click the item to view it then the original post is not visible - thus it remains in the archive and will be available if the slack account is upgraded - otherwise it remains hidden.

**Comment by tanto259** [comment]
I have no objections to any kind of usage guideline being prominently placed on the Open Mainframe Project's website. However, I believe the invite link to the Slack workspace is everywhere on the internet and we need to figure out how we can properly communicate the guideline to new users joining from other sources.

Some other proposals I have in mind:

- Restricting the #general channel to strictly posts by project committers and admins, so it should only be used for announcement or as a directory list to point users to the respective channels. This should be possible on the free Slack plan. It's a bit of a drastic measure, but right now everyone is automatically added to #general and there is no way to customize this behavior on the free Slack plan. We can then have another channel for workspace-wide discussions.

- Checking if GreetBot is still working, I believe it should have send every new users a DM with information.

- If for some reason we are able to get a Slack paid plan, it should be possible to set is such that invite links would be customizable to select default channels that new users will be automatically added to.

**Comment by lbdyck** [comment]
While the invite link is public and easily available to those who find it, the key is that individuals who join **need** to understand the participation guidelines which is not readily available at this point (at least I didn't find any).

1. I'm not a fan of locking down the `general` channel but it does need to have the fluff removed/limited.
2. I'm not familiar with GreenBot but having read up on it just now it does look worthwhile to implement and to provide the guidelines to new users
3. +1

While having **guidelines** is no guarantee that they will be read, understood, or followed, it is a start.

My $0.01 (not sure they are worth $0.02)

**Comment by tanto259** [comment]
> 1. I'm not a fan of locking down the `general` channel but it does need to have the fluff removed/limited.

Neither do I, but at this point it seems that many people would post stuff there without checking for the appropriate channel. It's been like that for a while and I sometimes noticed that important questions that people have for other projects got buried with all of the "fluff".

Not sure if there are any good (and free) way we can moderate posts there... I don't think Slack have any good moderation tools for large public communities...

> 2. I'm not familiar with GreenBot but having read up on it just now it does look worthwhile to implement and to provide the guidelines to new users

This is what is GreetBot should have posted to every new joins via DM. If you checked the link for the Slack Guidelines and Code of Conduct, it leads to a 404. So definitely need to update those links... There is some sort of a guideline at https://tac.openmainframeproject.org/tools/slack.html. But I agree with your suggestion that we probably need a more comprehensive one.

Then again, as you said, no guarantee that people will read the DM that GreetBot sent.

> **Welcome to the Open Mainframe Slack Workspace!**
>
>This workspace is for general discussion amongst Open Mainframe Project members and the broad community. Review the [Slack Guidelines](https://github.com/openmainframeproject/tac/blob/master/process/collaboration_tools.md#slack) and follow the [Open Mainframe Summit Code of Conduct](https://github.com/openmainframeproject/tac/blob/master/process/code-of-conduct.md). Here are some key channels to get started in.
>
>Check out the below channels for specific [projects and working groups hosted at OMP](https://www.openmainframeproject.org/projects)...
>
>[#ambitus](https://openmainframeproject.slack.com/archives/CNPSBA21E) - Ambitus
[#ade](https://openmainframeproject.slack.com/archives/C5EHS8DUH) - ADE
[#atomplugins](https://openmainframeproject.slack.com/archives/CGEDRG9RB) - Atom language syntax highlighting for z/VM
[#cobol-check](https://openmainframeproject.slack.com/archives/C01KU5GSTQS) - COBOL Check
[#cobol-programming-course](https://openmainframeproject.slack.com/archives/C011NE32Z1T) - COBOL Programming Course
[#wg-cobol](https://openmainframeproject.slack.com/archives/C01549LK4F8) - COBOL Working Group
[#consolez](https://openmainframeproject.slack.com/archives/C01L6LB1HQR) - ConsoleZ
[#cbt-tape](https://openmainframeproject.slack.com/archives/C01B0GVPR60) - CBT Tape
[#feilong](https://openmainframeproject.slack.com/archives/C5GTMN4LV) - Feilong
[#genevaers](https://openmainframeproject.slack.com/archives/C01711931GA) - GenevaERS
[#omp-education-project](https://openmainframeproject.slack.com/archives/CVAEXLDGU) - Mainframe Open Education
[#mentorship](https://openmainframeproject.slack.com/archives/C1BBXAC6L) - Mentorship program
[#wg-open-zos-enablement](https://openmainframeproject.slack.com/archives/C01H6FJ8NCS) - Open z/OS Enablement
[#polycephaly](https://openmainframeproject.slack.com/archives/C016LV85Z46) - Polycephaly
[#software-discovery-tool](https://openmainframeproject.slack.com/archives/C014X0ALFAT) - Software Discovery Tool
[#tersedecompress](https://openmainframeproject.slack.com/archives/CGEDR73EZ) - TerseDecompress
[#tessia](https://openmainframeproject.slack.com/archives/C01FTHD5NQ5) - Tessia
[#zorow](https://openmainframeproject.slack.com/archives/CJ97KV140) - Zorow
[#zowe-user](https://openmainframeproject.slack.com/archives/CC08782AG) or [#zowe-dev](https://openmainframeproject.slack.com/archives/CBW5ET69G) - Zowe
>
>Other good channels to check out....
>
>[#academic](https://openmainframeproject.slack.com/archives/C1BC6HS81) - Discussion for students or those in academia
[#marketing](https://openmainframeproject.slack.com/archives/C1BBT432A) - Events and other outreach happening
[#socialmedia](https://openmainframeproject.slack.com/archives/C014JF7A4EQ) - Share posts we can reshare on the OMP Twitter and LinkedIn
[#linuxone](https://openmainframeproject.slack.com/archives/CA4HYKG4D) - Discussion on Linux on Z
[#zos-beginners](https://openmainframeproject.slack.com/archives/CGREF2HJR) - z/OS discussion
[#zosmf-adoption](https://openmainframeproject.slack.com/archives/CGLJM7W4W) - z/OSMF discussion
>
>Feel free to reach out to [@jmertic](https://openmainframeproject.slack.com/team/U1BAJL5QB) or [@Maemalynn](https://openmainframeproject.slack.com/team/UCA2FR2F7) if you have any questions or need assistance.

**Comment by jmertic** [comment]
ACTIONS:

- Each project needs to establish and maintain its guidelines for each of its channel purposes, and guidelines posted as the subject/pin for each channel.
- Do analytics report on channel usage.
- Get a full list of channels for the group to review.
- Investigate automation tools to direct users out of general for messages, along with ways to better inform users of where to go.

**Comment by jmertic** [comment]
See attached full list of channels and analytics for the past 5 years:

[slack_main_channels.csv](https://github.com/openmainframeproject/tac/files/11627528/slack_main_channels.csv)

**Comment by jmertic** [comment]
@lbdyck is coming up with recommendations for using Greetbot

**Comment by lbdyck** [comment]
strawman for GreenBot:

{{members}} welcome to the Open Mainframe Project (OMP) Slack workspace that hosts channels specific to individual OMP sponsored activities and projects.  Please refer to this page for specifics on [best practices ](https://github.com/openmainframeproject/tac/blob/main/tools/slack.md) so that you will get the most benefit from this workspace.

One key thing to keep in mind with the number of available channels is to find the channel that most closely aligns with your reason for being here and then use that channel for your questions and posts.

**Comment by jmertic** [comment]
Action: Projects review their channels and update. Revisit in a few months.

**Comment by lbdyck** [comment]
It appears that Slackbot - which is already included - could help in some areas.

See more here https://slack.com/help/articles/202026038-An-introduction-to-Slackbot

One thing is it has the ability to generate an auto-response when keywords are found.

**Comment by lbdyck** [comment]
let's close it
