### ISSUE TITLE
Annual Review - Software Discovery Tool - 5/25

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#493]
@pleia2 Confirming you are good to go today - let us know /cc @yarille

**Comment by pleia2** [comment]
I'm ready! Notes that I'll present at the meeting are available here: https://docs.google.com/document/d/1Li3FPxX7xECuUp1JTTrDrFw1Rcg1JNXkwKjzbcj_gGQ/edit?usp=sharing

**Comment by jmertic** [comment]
Approved via email - @yarille please update the review dates and then close this
