### ISSUE TITLE
TerseDecompress - Annual Review

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#505]
@alexgubanow Can you be ready for this during the 7/27 TAC meeting?

**Comment by alexgubanow** [comment]
What does annual review would mean for this project?

**Comment by jmertic** [comment]
@alexgubanow details at https://tac.openmainframeproject.org/process/review_cycle.html. Can we schedule for 8/10?

**Comment by alexgubanow** [comment]
Yes, please. I was not able to join last time, it seem like link I have is from April. Will try to get a correct link this time.

**Comment by jmertic** [comment]
Thanks! @yarille can you make sure @alexgubanow has the correct invite?

**Comment by yarille** [comment]
Renewed by TAC email vote, 9/6/2023.
