### ISSUE TITLE
GenevaERS Annual Review- 08/10

### ISSUE THREAD

**Issue by yarille** [openmainframeproject/tac#525]
### Please share any additional details on this topic

GenevaERS Annual Review

### Detail what actions or feedback you would like from the TAC

GenevaERS Annual Review

### How much time do you need for this topic?

10 minutes or less

**Comment by jmertic** [comment]
Waiting for vote @yarille

**Comment by yarille** [comment]
renewed via TAC email vote 9/6/2023
