### ISSUE TITLE
OpenTelemetry SIG formation

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#535]
### Please share any additional details on this topic

There is an OpenTelemetry SIG forming to augment the OpenTelemetry standard and build agents/collectors for z/OS and z/Linux. 

### Detail what actions or feedback you would like from the TAC

Awareness and getting interest for others to participate.

### How much time do you need for this topic?

None

**Comment by v1gnesh** [comment]
Hi @jmertic, are you able to invite me to the (cloud-native) slack and the meetings referred to [here](https://github.com/open-telemetry/community/issues/1686). Would like to tune in as someone in the field.

**Comment by jmertic** [comment]
You can create an account at https://slack.cncf.org/, and then join the channel at https://cloud-native.slack.com/archives/C05PXDFTCPJ

**Comment by v1gnesh** [comment]
@jmertic Is this right? It goes to this page, where the Subject CN is **sharp-hawking.139-59-112-81.plesk.page**.

![image](https://github.com/openmainframeproject/tac/assets/234149/f5174e68-a53b-4c13-8a65-c88482c44cb6)

**Comment by jmertic** [comment]
Hmm - can you comment on the proposal at https://github.com/open-telemetry/community/pull/1687 to express interest and ask about joining the Slack channel? Not sure why that forward isn't working.

**Comment by v1gnesh** [comment]
@jmertic No luck yet on the comment in the OTel PR. Please advise..

**Comment by jmertic** [comment]
The instructions listed I just verified working; can you try again?

**Comment by v1gnesh** [comment]
Still seeing the same - https://github.com/open-telemetry/community/pull/1687#issuecomment-1803056316

**Comment by jmertic** [comment]
SIG is launching! Register interests at https://github.com/open-telemetry/community/pull/1687
