### ISSUE TITLE
Secure access to OMP

### ISSUE THREAD

**Issue by v1gnesh** [openmainframeproject/tac#550]
Ideally, before users/projects are onboarded to the infra, a plan for secure access needs to be in place.

For Linux on Z at least, I see this as an opportunity to use new tech, and to work more with startups.

Continuing what's mentioned [here](https://github.com/openmainframeproject/tac/pull/481#issuecomment-1618280856)...
[Tailscale](https://tailscale.com) is a zero-hassle solution on top of a very light-weight and performant VPN technology that's built for today - WireGuard.

Tailscale supports workflows related to SSH and makes it as easy as peasy to work with SSH targets from VS Code (for example). VS Code supports SSH & remote developement already, sure; but with Tailscale, it's seamless.
https://tailscale.com/blog/machine-explorer-vscode-extension/

Sure, the choices are limited based on who's involved, what's currently in use, etc.
As a Z enthusiast, I strongly suggest that this tech is reviewed.
In my view, mainframe / IBM should take every opportunity to demonstrate new tech on Z.
They are chances to show both the strengths of the platform & boost startups whose tech pairs well with scale-up. 

This needn't be recurring item or even on the call; just something that would be nice if it happened.
Note that WireGuard will very likely be the successor to IPSec.
So the time investment in WG / Tailscale isn't just for this use case.
WG could very well have a future in zOS Comms Server.

**Comment by jmertic** [comment]
Not sure of an action for the TAC - closing.
