### ISSUE TITLE
2024 Ambassador Selections

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#590]
### Please share any additional details on this topic

We would like to open up the call for Ambassadors for 2024. Proposed timeline.

November 8, 2023 - Open Call for Ambassadors
December 7, 2023 - Close Call for Ambassadors
December 8-14, 2023 - TAC Voting members ranking nominees.
December 14, 2023 - TAC members confirm Ambassadors selections
January 2024 - New Ambassadors publically announced.

### Detail what actions or feedback you would like from the TAC

Confirm timeline and approve moving forward.

### How much time do you need for this topic?

20 minutes

**Comment by jmertic** [comment]
TAC approved plan 11/9

List of applicants at https://github.com/openmainframeproject/tac/labels/ambassador-application

**Comment by jmertic** [comment]
TAC voting via email on final selections, then staff will do notifications

@yarille please close once the vote is done.

**Comment by yarille** [comment]
Ambassadors were chosen and voted by TAC- Jan. 2024
