### ISSUE TITLE
Ambassador application - Sujit Neb

### ISSUE THREAD

**Issue by sneb-bmc** [openmainframeproject/tac#599]
### Email

sujit.neb@gmail.com

### Bio

I am highly skilled in Mainframe DevOps and a Linux Engineer with total 13 years of
experience specializing in CI/CD pipelines using Jenkins, GitHub Actions, Azure DevOps and GitLab etc.. Also, Leading the Test Automation and optimizing software development workflows here at BMC Software.  Proven history of
enhancing system reliability, streamlining deployment processes, and fostering a culture of agility.

### Projects within OMP you would want to be an ambassador for

Galasa and/ Zowe and/or Tessia

### List any other topics you would be able to speak about

Test Automation 
Python for z/OS
zCX - Container extension for zOS
Containerization/Docker

### Why do you want to be an ambassador?

As an aspiring ambassador for the Open Mainframe Project, I am deeply passionate about the transformative potential of mainframe technology in the modern computing landscape. It will also allow me to facilitate knowledge exchange within the mainframe community. I am curious about demystifying mainframe technology and promoting its relevance in today's rapidly evolving tech landscape. As an ambassador, I will be able to actively contribute to educational initiatives, ensuring that the benefits and capabilities of mainframes are widely understood and appreciated. Last but not the least, the OMP embodies collaboration, innovation, and the open-source ethos, which resonates with my values and vision for the future. 

### Attach a headshot

![new](https://github.com/openmainframeproject/tac/assets/126774289/c1b7f521-8e3a-44c2-a35c-fa47d986cf9a)

**Comment by jmertic** [comment]
Thank you @sneb-bmc! We adjusted the form to submit via Hubspot; would you mind re-applying at https://share.hsforms.com/1HYumUOu_QUOsVZZH9D7IUA4tvhy? Sorry for the inconvenience.

**Comment by yarille** [comment]
Voted by TAC as new Ambassador for 2024
