### ISSUE TITLE
Elliot Jalley

### ISSUE THREAD

**Issue by jalel01** [openmainframeproject/tac#601]
### Email

elliot.jalley@broadcom.com

### Bio

In my current role as a Product Manager at the Broadcom Mainframe R&D Centre in Prague, i am focused on modernizing the way we work with the mainframe, in particular via the adoption of REST APIs, to help infrastructure teams deliver applications faster, more efficiently and with higher quality. 
Previous to this role, i have been heavily invested in improving the maintenance experience for z/OS software.
In my 25 years as product manager i have been fortunate to be part of a number of diffferent industries, often at a point of inflection. Such as the Telecommunications industry in the early 2000's and the dawn of the iPhone, or the Gaming industry in the 2010's as mobile and social gaming exploded.

### Projects within OMP you would want to be an ambassador for

Zowe

### List any other topics you would be able to speak about

Mainframe Modernization
Mainframe REST APIs
Mainframe Education
Mainframe Automation
Mainframe Insights

### Why do you want to be an ambassador?

I have been part of the Zowe project from its inception and have contributed to both the client side and the server components. I am an evangelist for Zowe both within my organisation (Broadcom) and towards the wider community. I have a specific interest in the Zowe API Mediation Layer and how it can be used to manage infrastructure APIs. I am a proponent for using these APIs to enable IT teams to modernize and automate their infrastructure. I am fully committed to growing the Zowe eco-system to help make the mainframe like any another hybrid cloud platform.  

### Attach a headshot

![elliotcrop](https://github.com/openmainframeproject/tac/assets/47416452/d9a1bcc0-97dd-403e-b273-822d01cdf6bc)

**Comment by jmertic** [comment]
Thank you @jalel01! We adjusted the form to submit via Hubspot; would you mind re-applying at https://share.hsforms.com/1HYumUOu_QUOsVZZH9D7IUA4tvhy? Sorry for the inconvenience.

**Comment by yarille** [comment]
Voted by TAC as new Ambassador for 2024
