### ISSUE TITLE
Ambassador application - Darren Surch

### ISSUE THREAD

**Issue by DarrenSurch** [openmainframeproject/tac#602]
### Email

dsurch@interskill.com

### Bio

Darren Surch is 1 of 32 'Lifetime' IBM Champions ever named by IBM and only the 2nd Lifetime IBM Champion ever named for IBM Z. IBM Champions are a select global community of 700+ external experts, across all IBM technologies, recognized by IBM for thought leadership, extraordinary expertise and outstanding contributions to the IBM technical community. Darren is a respected industry expert on mainframe workforce training and a noted speaker at mainframe computing conferences and events worldwide.

Darren is CEO of Interskill Learning, the world's most delivered mainframe training. Darren and Interskill have collaborated with the Open Mainframe Project for a number of years to develop a 3-hour "Zowe Foundations" elearning course that Interskill provides to the world free of charge to help build Zowe proficiency globally. Darren and Interskill also award the Open Mainframe Project's "Fundamentals for Zowe" digital credential to all people completing the course. With over 7,000 of this OMP Zowe badge and the older IBM Zowe badge awarded, this has made a significant impact on Zowe proficiency globally! Also of note, Darren and Interskill are currently working with OMP and the Zowe project to develop a second advanced Zowe course for release in early 2024.    

### Projects within OMP you would want to be an ambassador for

Zowe

### List any other topics you would be able to speak about

Mainframe workforce training
Zowe education
Digital credentialing

### Why do you want to be an ambassador?

I look forward to continuing my collaboration with the Open Mainframe Project to ensure the global availability of quality, free Zowe education, powered by bragworthy digital credentials that drive course completions and spread awareness of Zowe across the mainframe industry. While I am not your typical "technical" Open Mainframe Ambassador who contributes code and technical input, I hope that my past work lifting Zowe, my global mainframe education knowledge and experience, my prominence in the mainframe space as 1 of only 2 Lifetime IBM Champions for IBM Z, and my ability to assist driving global Zowe skills and product awareness, will all qualify me as an Open Mainframe Ambassador. As I have shown for many years, I am here to help the OMP. Thank you for your consideration!

Here is an article from your Open Mainframe Project Blog - https://openmainframeproject.org/blog/its-zowes-5th-anniversary-and-here-are-your-gifts/

### Attach a headshot

![Darren Surch - casual - 2022](https://github.com/openmainframeproject/tac/assets/152436361/5e377159-c1fd-4a4e-9bf4-8d7e09a23365)

**Comment by yarille** [comment]
Voted by TAC as new Ambassador for 2024

**Comment by DarrenSurch** [comment]
What an honor! Thank you TAC!
