### ISSUE TITLE
Ambassador application - Jan Prihoda

### ISSUE THREAD

**Issue by jp669844** [openmainframeproject/tac#603]
### Email

jan.prihoda@broadcom.com

### Bio

Jan is an experienced Product Owner at Broadcom responsible for Zowe support, software management standardization, and automation. He has long experience in software development in the telecommunication industry and now he is trying to combine his experience and mainframe complexity to bring new ideas.

### Projects within OMP you would want to be an ambassador for

Zowe

### List any other topics you would be able to speak about

z/OSMF Software Management - Portable Software Instances, z/OSMF workflows
Ansible - z/OS Software Management Automation, mainframe automation orchestration

### Why do you want to be an ambassador?

I'm already talking a lot in front of the mainframe community at various conferences about Zowe directly or as a part of other solutions. It would be nice to do it more "formally". :) 

### Attach a headshot

![mypic](https://github.com/openmainframeproject/tac/assets/55390120/c283b05c-5b13-4c49-8ec2-771e2dd3b0ab)

**Comment by jmertic** [comment]
Thank you @jp669844! We adjusted the form to submit via Hubspot; would you mind re-applying at https://share.hsforms.com/1HYumUOu_QUOsVZZH9D7IUA4tvhy? Sorry for the inconvenience.

**Comment by jp669844** [comment]
Np, done

**Comment by jmertic** [comment]
Thanks!
