### ISSUE TITLE
Intro to OpenTelemetry on Mainframe SIG

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#616]
### Please share any additional details on this topic

There has been a recent SIG launched on OpenTelemetry on Mainframe. @rrschulze will do a presentation on the group and how to get involved/leverage the work.

More on the SIG at https://github.com/open-telemetry/community/blob/main/projects/mainframe.md

### Detail what actions or feedback you would like from the TAC

Awareness and ideas for alignment/engagement

### How much time do you need for this topic?

20 minutes

**Comment by rrschulze** [comment]
OpenTelemetry is a vendor-agnostic, open-source framework for observability and a CNCF incubating project. OpenTelemetry has seen a tremendous adoption over the last years and is about to become the de-facto open-standard for observability and telemetry distribution. 

The new SIG OpenTelemetry on Mainframe of OpenTelemetry project is focused on enabling OpenTelemetry on the Mainframe for an improved end-to-end observability.

In the session today, I will give an introduction to OpenTelemetry and then discuss the goals of the new SIG and how to engage. We welcome long-time mainframers and those who are new to platform and want to learn about mainframe technology.

20 mins is fine for the presentation. I will attach the slides of presentation here after the call today.
