### ISSUE TITLE
New calendar for LFX Meetings

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#656]
### Please share any additional details on this topic

There is a new calendar available for projects using LFX meetings, see link below.

https://calendar.openmainframeproject.org

We can also do sub-project specific calendars...

https://calendar.zowe.org

### Detail what actions or feedback you would like from the TAC

Awareness and determine timing of decommissioning calendars at lists.openmainframeproject.org

### How much time do you need for this topic?

5 minutes or less

**Comment by jmertic** [comment]
@jmertic to follow up on how to do email reminders of meetings to mailing lists

**Comment by v1gnesh** [comment]
Please add zOS Open Tools :)
For info @igortodorovskiibm

**Comment by jmertic** [comment]
Hey @v1gnesh - this will be added automatically once the Technical Charter is complete for the project.
